<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Attachment</name>
   <tag></tag>
   <elementGuidId>05167d23-a321-4fdf-9487-20b029d79fd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='Attachment']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Attachment</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'Attachment' and (text() = 'Attachment' or . = 'Attachment')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5eb1d986-d06c-4a17-a336-1417e25210d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Attachment</value>
      <webElementGuid>13974e2a-27bc-44d1-accd-4d9ef91a332b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>BTN</value>
      <webElementGuid>7aa5b715-3165-4366-b5b9-eee6f65fb3fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Attachment</value>
      <webElementGuid>80b270fb-2f99-476d-b547-a46f29a25b2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='Attachment']</value>
      <webElementGuid>6d70976a-c7ee-4c6b-b99d-98bbdcf834a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[3]/div/div[4]/button</value>
      <webElementGuid>c93d055e-2805-45cf-a226-e35cafd1a5ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Line Approvals'])[1]/following::button[1]</value>
      <webElementGuid>040986ea-fabd-4b01-b971-4bf84e08ba8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::button[2]</value>
      <webElementGuid>41b56fbf-5c30-4fc0-973d-ea0e6c493a9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='History'])[1]/preceding::button[1]</value>
      <webElementGuid>ef0d5b1b-a68a-471d-b4a5-7bac63a22d55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div/div[4]/button</value>
      <webElementGuid>a3528ba5-0ed1-4de4-8205-7b67545b6f1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'Attachment' and (text() = 'Attachment' or . = 'Attachment')]</value>
      <webElementGuid>a9df55d6-c18f-4c02-a84d-d3b1d3f2582b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
