<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_New Request SubmitSave DraftRequestorIn_7e3c92</name>
   <tag></tag>
   <elementGuidId>e19cdbd2-ff93-4fc2-b1f1-6488d3576048</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.request-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ff628fea-c716-4eed-9ad8-7c761961ee03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>request-container</value>
      <webElementGuid>6c49382a-fce3-4ae6-9f2e-54b20ed7f50c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> New Request SubmitSave DraftRequestorInformationLine ApprovalsAttachmentRequestorInformationLine ApprovalsAttachmentInformationKTL-VLD01: Validation FormNew RequestAuto GenerateRequest Dateวันที่ร้องขอเอกสาร11 Feb 2023Company *บริษัท Toเรียน CC :สำเนา Subject *เรื่องTest Validation By Katalon วันที่กำหนดเสร็จ *due dateชื่อ-สกุล fullname</value>
      <webElementGuid>282b570e-9a11-4c58-ab1a-b03d946cb480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;request-main-container&quot;]/div[@class=&quot;request-container&quot;]</value>
      <webElementGuid>5c8e7d3d-3355-4312-8908-6fce97f08442</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div</value>
      <webElementGuid>0d537f85-b4d2-49d6-85d9-621ee7f65281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div</value>
      <webElementGuid>a97f7033-462c-4d79-a217-16a2ad305873</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' New Request SubmitSave DraftRequestorInformationLine ApprovalsAttachmentRequestorInformationLine ApprovalsAttachmentInformationKTL-VLD01: Validation FormNew RequestAuto GenerateRequest Dateวันที่ร้องขอเอกสาร11 Feb 2023Company *บริษัท Toเรียน CC :สำเนา Subject *เรื่องTest Validation By Katalon วันที่กำหนดเสร็จ *due dateชื่อ-สกุล fullname' or . = ' New Request SubmitSave DraftRequestorInformationLine ApprovalsAttachmentRequestorInformationLine ApprovalsAttachmentInformationKTL-VLD01: Validation FormNew RequestAuto GenerateRequest Dateวันที่ร้องขอเอกสาร11 Feb 2023Company *บริษัท Toเรียน CC :สำเนา Subject *เรื่องTest Validation By Katalon วันที่กำหนดเสร็จ *due dateชื่อ-สกุล fullname')]</value>
      <webElementGuid>4f1a0359-3457-43cc-981e-9378f5c05465</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
