<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_-_items1.layout1.data.value (1)</name>
   <tag></tag>
   <elementGuidId>e96ea36d-07dc-49bd-8709-41944904af4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;items[1].layout[1].data.value&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='items[1].layout[1].data.value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ed82b504-cb55-4eb9-ac35-17bf5b0a8145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>items[1].layout[1].data.value</value>
      <webElementGuid>226fb53f-2785-4185-b46b-00c91fc290f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-lg input-component</value>
      <webElementGuid>4ee7ffe0-691f-43ea-848d-9972b944fcc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ddc8a645-1d5e-480c-8cce-6b201ab476bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ขวัญใจ เจริญผลวัฒนา</value>
      <webElementGuid>050853bf-b5d7-4495-8d61-84b4b9e6a7d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic&quot;)/div[@class=&quot;set-padding-core-control row&quot;]/div[@class=&quot;padding-controller col-xl-4 col-md-4 col-sm-12 col-12&quot;]/div[@class=&quot;input-component-container&quot;]/input[@class=&quot;ant-input ant-input-lg input-component&quot;]</value>
      <webElementGuid>a6892ddb-b369-4ebd-94aa-dadc4f3bf336</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='items[1].layout[1].data.value']</value>
      <webElementGuid>b1add358-3c44-4c51-a9ab-54d626eb5af3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div[2]/div[4]/div/input</value>
      <webElementGuid>4bb5af9b-47da-4007-a144-0ac32f238cc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>af8f9754-4745-49a0-ad55-904f11afbff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'items[1].layout[1].data.value' and @type = 'text']</value>
      <webElementGuid>953236f0-b6c5-46b2-bf82-13125c10c6bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
