<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_d</name>
   <tag></tag>
   <elementGuidId>d6cf0b3a-9f85-4ac2-8f45-d3cbaf5aeb92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='basic']/div[2]/div[2]/div/div/div/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ant-select-selection-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>067e3bd8-abf9-4cb6-9420-141d9dde3ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-selection-item</value>
      <webElementGuid>8749c277-250f-466d-aa98-29759a5fa48a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>d</value>
      <webElementGuid>3b0a4f6a-f1e9-4ced-aa96-bae1207de4dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>d</value>
      <webElementGuid>bfa66503-6197-46a9-9310-af2c8ce3b988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic&quot;)/div[@class=&quot;set-padding-core-control row&quot;]/div[@class=&quot;padding-controller col-xl-4 col-md-4 col-sm-12 col-12&quot;]/div[@class=&quot;input-component-container&quot;]/div[@class=&quot;ant-select ant-select-lg ant-select-focused ant-select-single ant-select-show-arrow ant-select-open ant-select-show-search&quot;]/div[@class=&quot;ant-select-selector&quot;]/span[@class=&quot;ant-select-selection-item&quot;]</value>
      <webElementGuid>0678ed39-3a1f-4432-9e75-f57d6fe9dc15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div[2]/div[2]/div/div/div/span[2]</value>
      <webElementGuid>68aa1f9d-cc34-489d-ade1-19b0ee99afb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ประเภทค่าใช้จ่าย'])[1]/following::span[2]</value>
      <webElementGuid>8af253c3-fcd0-4148-8398-cde729e73532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ชื่อสินค้า'])[1]/preceding::span[4]</value>
      <webElementGuid>6f884719-e449-4ebd-acd9-5ed3710ee618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ราคา'])[1]/preceding::span[5]</value>
      <webElementGuid>17ed2282-1ca1-4cfb-8e13-07d36e7e7184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='d']/parent::*</value>
      <webElementGuid>fc8c1c5e-39a2-4e57-8a3b-17a8517ba5df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/span[2]</value>
      <webElementGuid>ff90b89c-4709-427b-93a7-f96e80e8acfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'd' and (text() = 'd' or . = 'd')]</value>
      <webElementGuid>7a2f9cf4-6b44-4889-9a90-d927d7a71d55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
