<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_c</name>
   <tag></tag>
   <elementGuidId>1c0b996b-fd73-45d8-a1a8-e4f213bc9110</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='basic']/div[2]/div[2]/div/div/div/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ant-select-selection-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>29954030-69d8-4a68-b086-2b753a790363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-selection-item</value>
      <webElementGuid>8bf415d9-875b-4da7-9294-76cd2fdf29c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>c</value>
      <webElementGuid>ce95652d-5150-40ba-8b89-bf2d3a12e531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>c</value>
      <webElementGuid>d4b8a6e6-861b-4fe6-9c6f-e1d9f773f79e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic&quot;)/div[@class=&quot;set-padding-core-control row&quot;]/div[@class=&quot;padding-controller col-xl-4 col-md-4 col-sm-12 col-12&quot;]/div[@class=&quot;input-component-container&quot;]/div[@class=&quot;ant-select ant-select-lg ant-select-focused ant-select-single ant-select-show-arrow ant-select-open ant-select-show-search&quot;]/div[@class=&quot;ant-select-selector&quot;]/span[@class=&quot;ant-select-selection-item&quot;]</value>
      <webElementGuid>156aa66a-3825-4e8b-bdbe-61eb479055bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div[2]/div[2]/div/div/div/span[2]</value>
      <webElementGuid>4c57c9bb-c2d3-4c8d-86d5-76a458f900b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ประเภทค่าใช้จ่าย'])[1]/following::span[2]</value>
      <webElementGuid>98b25a9c-92f6-4447-b015-8be4f05e731e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ชื่อสินค้า'])[1]/preceding::span[4]</value>
      <webElementGuid>2dfec803-1496-4d50-b8bf-092f2429c031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ราคา'])[1]/preceding::span[5]</value>
      <webElementGuid>d0cfc5d4-9520-47dc-acec-4d3d26397ec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='c']/parent::*</value>
      <webElementGuid>889ffc7c-3996-46fe-bf3f-0eb60069ac2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/span[2]</value>
      <webElementGuid>2dca6db0-4c36-489b-b896-8b51877a77ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'c' and (text() = 'c' or . = 'c')]</value>
      <webElementGuid>0f784309-51ca-45bc-abc9-0d30ee17226f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
