<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_-confirm-</name>
   <tag></tag>
   <elementGuidId>2b675280-b7b5-49df-8075-1f2fe1ea5db7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.rps_ae04 > div > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ReadingPaneContainerId']/div/div/div/div[2]/div/div/div/div/div/div/div/div[3]/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>16c4f206-06c5-4cf5-8788-4359f5a092a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://qar2.wolfapprove.com/Verify?PK=07fb1c27-939a-4a36-b1dd-8de792abbed5</value>
      <webElementGuid>00fdbf6c-44da-4d21-a26d-54b72c1978e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>632831bc-0c29-4dc5-b76f-9f746e58b754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener noreferrer</value>
      <webElementGuid>b1406001-fbf6-419e-b524-6643eaac0c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-auth</name>
      <type>Main</type>
      <value>NotApplicable</value>
      <webElementGuid>ba0c49dc-581c-4eaa-8ce3-30b3ad605e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-safelink</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d1f28d6a-dcf6-4abf-a060-1121da24c3b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-linkindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>55b278cd-e76e-437b-a4c1-cc10f03ba265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-confirm-</value>
      <webElementGuid>305a4e52-c005-4b18-8c56-7eb483b5f7ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReadingPaneContainerId&quot;)/div[1]/div[@class=&quot;g_zET&quot;]/div[@class=&quot;MtujV&quot;]/div[@class=&quot;L72vd&quot;]/div[@class=&quot;Q8TCC yyYQP customScrollBar&quot;]/div[1]/div[@class=&quot;aVla3&quot;]/div[1]/div[1]/div[@class=&quot;wide-content-host&quot;]/div[@class=&quot;SlLx9 isFirstCard byzS1&quot;]/div[@class=&quot;XbIp4 jmmB7 GNqVo yxtKT allowTextSelection&quot;]/div[1]/div[@class=&quot;rps_ae04&quot;]/div[1]/a[1]</value>
      <webElementGuid>9ba6f9c8-e428-4b64-8a2a-b3e3e8a26a15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ReadingPaneContainerId']/div/div/div/div[2]/div/div/div/div/div/div/div/div[3]/div/div/div/a</value>
      <webElementGuid>adef69e3-e70a-4fa5-803d-424f7fa129cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'-confirm-')]</value>
      <webElementGuid>22222ac6-2a9e-4796-bea4-2083c398e9fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wed 1/18/2023 4:46 PM'])[1]/following::a[1]</value>
      <webElementGuid>8732d534-6a24-4549-b82f-56d051797c3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Potjanee Jienphan'])[2]/following::a[1]</value>
      <webElementGuid>e0dfba51-34a3-4563-9e23-11fdc22aa3ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reply'])[3]/preceding::a[1]</value>
      <webElementGuid>f85d324f-cc76-41ab-b435-92c298916018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reply all'])[3]/preceding::a[1]</value>
      <webElementGuid>70e87d2a-eb30-490f-93d0-2843f01c1b61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='-confirm-']/parent::*</value>
      <webElementGuid>93f9f680-2444-46c1-ad50-96bdb708fbbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://qar2.wolfapprove.com/Verify?PK=07fb1c27-939a-4a36-b1dd-8de792abbed5')]</value>
      <webElementGuid>30657122-a2cd-460a-aad7-99b3c4d03273</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/a</value>
      <webElementGuid>90251a57-f223-4631-9846-b3cbf4bc1ef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://qar2.wolfapprove.com/Verify?PK=07fb1c27-939a-4a36-b1dd-8de792abbed5' and (text() = '-confirm-' or . = '-confirm-')]</value>
      <webElementGuid>d422ad42-9992-4df1-9da0-9559590055c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
