<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_workflow mailReplyReply allForwardMore _0a2416</name>
   <tag></tag>
   <elementGuidId>b884b126-fec1-4b42-9f08-0dd1909b53e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.SlLx9.isFirstCard.byzS1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ReadingPaneContainerId']/div/div/div/div[2]/div/div/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9abe6597-3b71-4547-ade2-b2c27131996d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d70e1224-ccc4-450f-b5cd-ecf03041fd24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Email message</value>
      <webElementGuid>1a8164be-5022-4866-90e2-2107b96e0540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SlLx9 isFirstCard byzS1</value>
      <webElementGuid>9ea83b7d-e70f-4d62-ba6e-563e84923746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>workflow mailReplyReply allForwardMore actionsTo:workflow mail;Nijjaree Phadee;Kanita Jubsung;Natthakarn Yaemngamluae;Potjanee JienphanCc:workflow mail;Nijjaree Phadee;Kanita Jubsung;Natthakarn Yaemngamluae;Potjanee JienphanWed 1/18/2023 4:46 PMDear user     Please confirm to change password for access WOLF Approve-confirm-[THIS IS AN AUTOMATED MESSAGE - PLEASE DO NOT REPLY DIRECTLY TO THIS EMAIL]To : wolf01@qar2.comCC : ReplyReply allForward</value>
      <webElementGuid>4e6f7319-f14b-4b02-abb0-e0f108db4bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReadingPaneContainerId&quot;)/div[1]/div[@class=&quot;g_zET&quot;]/div[@class=&quot;MtujV&quot;]/div[@class=&quot;L72vd&quot;]/div[@class=&quot;Q8TCC yyYQP customScrollBar&quot;]/div[1]/div[@class=&quot;aVla3&quot;]/div[1]/div[1]/div[@class=&quot;wide-content-host&quot;]/div[@class=&quot;SlLx9 isFirstCard byzS1&quot;]</value>
      <webElementGuid>58a7ef1e-f273-4059-b778-477ca6a0f4ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ReadingPaneContainerId']/div/div/div/div[2]/div/div/div/div/div/div/div</value>
      <webElementGuid>ff34b4b9-8398-47e1-85cc-1367b567215f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This mail appears in Focused based on how you interact with the sender.'])[1]/following::div[8]</value>
      <webElementGuid>88ca3b95-a3a0-4ef4-98f7-7269e3baf4dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[WOLF Approve] Confirm to change password'])[2]/following::div[13]</value>
      <webElementGuid>1642ce8c-d6dc-455f-b561-5005bbf7ef6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/div/div/div/div/div/div/div</value>
      <webElementGuid>98b20d7c-15d1-4d33-9f30-0f708498b725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'workflow mailReplyReply allForwardMore actionsTo:workflow mail;Nijjaree Phadee;Kanita Jubsung;Natthakarn Yaemngamluae;Potjanee JienphanCc:workflow mail;Nijjaree Phadee;Kanita Jubsung;Natthakarn Yaemngamluae;Potjanee JienphanWed 1/18/2023 4:46 PMDear user     Please confirm to change password for access WOLF Approve-confirm-[THIS IS AN AUTOMATED MESSAGE - PLEASE DO NOT REPLY DIRECTLY TO THIS EMAIL]To : wolf01@qar2.comCC : ReplyReply allForward' or . = 'workflow mailReplyReply allForwardMore actionsTo:workflow mail;Nijjaree Phadee;Kanita Jubsung;Natthakarn Yaemngamluae;Potjanee JienphanCc:workflow mail;Nijjaree Phadee;Kanita Jubsung;Natthakarn Yaemngamluae;Potjanee JienphanWed 1/18/2023 4:46 PMDear user     Please confirm to change password for access WOLF Approve-confirm-[THIS IS AN AUTOMATED MESSAGE - PLEASE DO NOT REPLY DIRECTLY TO THIS EMAIL]To : wolf01@qar2.comCC : ReplyReply allForward')]</value>
      <webElementGuid>16fba2a9-dc2b-42d1-8840-c5d30cc9eca7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
