<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_workflow mailWOLF Approve Confirm to ch_d66a51</name>
   <tag></tag>
   <elementGuidId>9eaa89b9-7f63-4427-96ba-7742e7873c7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.XG5Jd.JtO0E</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AQAAARaO2ogBAAADql7vtQAAAAA=']/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fa4080a4-f2a0-4c41-8870-c773ec26c3c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>XG5Jd JtO0E</value>
      <webElementGuid>6ef1d64c-86cb-4a47-8553-cc4bcfcf7a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>workflow mail[WOLF Approve] Confirm to change password4:46 PMDear user Please confirm to change password for access WOLF Approve -confirm- [THIS IS AN AUTOMATED MESSAGE - PLEASE DO NOT REPLY DIRECTLY TO THIS EMAIL] To : wolf01@qar2.com CC :</value>
      <webElementGuid>8eb44a52-6b2a-46ff-9114-2dd92c29c6ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AQAAARaO2ogBAAADql7vtQAAAAA=&quot;)/div[1]/div[@class=&quot;zKDWD YbB6r IKvQi IjQyD JCRRb cSOXK G1NES&quot;]/div[@class=&quot;XG5Jd JtO0E&quot;]</value>
      <webElementGuid>1ca4ec67-d0e3-4604-a37f-7293ab68bb15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AQAAARaO2ogBAAADql7vtQAAAAA=']/div/div/div</value>
      <webElementGuid>db94af77-8389-4e4c-9c71-6178a00f29ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>4d28b849-05e6-41c8-a5b7-39863735025c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'workflow mail[WOLF Approve] Confirm to change password4:46 PMDear user Please confirm to change password for access WOLF Approve -confirm- [THIS IS AN AUTOMATED MESSAGE - PLEASE DO NOT REPLY DIRECTLY TO THIS EMAIL] To : wolf01@qar2.com CC :' or . = 'workflow mail[WOLF Approve] Confirm to change password4:46 PMDear user Please confirm to change password for access WOLF Approve -confirm- [THIS IS AN AUTOMATED MESSAGE - PLEASE DO NOT REPLY DIRECTLY TO THIS EMAIL] To : wolf01@qar2.com CC :')]</value>
      <webElementGuid>1474437f-d400-4d63-8f8c-a862b760cfa0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
