<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>dc279d28-8c25-4803-8dde-379a20cd8ba6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.button-confirm-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>70088920-4379-43cb-afde-f0deb0bb22d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-confirm-2</value>
      <webElementGuid>8e4de4af-6538-433c-8cbb-833fd466bc33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1e0225eb-6608-4657-85a4-158909d73dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ย้อนกลับไปหน้าเข้าสู่ระบบ</value>
      <webElementGuid>29531a8b-975b-4ea8-ae84-bbf52c0686e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;error-page-container without-nav&quot;]/div[@class=&quot;forget-password-container&quot;]/div[@class=&quot;text-container&quot;]/button[@class=&quot;button-confirm-2&quot;]</value>
      <webElementGuid>a4eaa26f-cc89-494f-95c8-a980410b292b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>c96b46a9-4785-4fc8-8600-cca0f6866d9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/button</value>
      <webElementGuid>6f4ab8c3-85c3-48b4-9529-b922a096bde9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ย้อนกลับไปหน้าเข้าสู่ระบบ']/parent::*</value>
      <webElementGuid>aae3953b-dc34-43ee-a39f-88f4fe9053cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>533c35fd-6b11-44c5-a64a-6aa3c34e77ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'ย้อนกลับไปหน้าเข้าสู่ระบบ' or . = 'ย้อนกลับไปหน้าเข้าสู่ระบบ')]</value>
      <webElementGuid>948986bb-dd2d-4e93-a50c-db52316c5a7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
