<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_worklist_subject</name>
   <tag></tag>
   <elementGuidId>fef897ae-0dbf-4c90-aa7e-ae471eac6b80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='แบบฟอร์มเบิกเงินสดย่อย_/_Petty_Cash_Voucher']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@class = 'p-inputtext p-component p-filled information-inputTexta-width' and @id = 'แบบฟอร์มเบิกเงินสดย่อย_/_Petty_Cash_Voucher' and @value = 'แบบฟอร์มเบิกเงินสดย่อย / Petty Cash Voucher']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad31a25a-7343-491e-9515-dc51d1a53e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-filled information-inputTexta-width</value>
      <webElementGuid>c4e8d92c-8a12-4fb3-94d1-290a979e867e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>แบบฟอร์มเบิกเงินสดย่อย_/_Petty_Cash_Voucher</value>
      <webElementGuid>5481596b-79af-4884-92a8-fab04357efb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>แบบฟอร์มเบิกเงินสดย่อย / Petty Cash Voucher</value>
      <webElementGuid>2e4ccf7d-fd7b-4669-a9ab-e0da123bb6cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;แบบฟอร์มเบิกเงินสดย่อย_/_Petty_Cash_Voucher&quot;]</value>
      <webElementGuid>4b348c64-8162-4502-8b58-c7a6b48e7ec9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='แบบฟอร์มเบิกเงินสดย่อย_/_Petty_Cash_Voucher']</value>
      <webElementGuid>3beb4f8e-f4ad-4d10-a76d-46dada140514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[4]/div/div[2]/div/div[3]/div[5]/div[2]/div/span/input</value>
      <webElementGuid>e42753e9-1c8c-44cd-9345-4a243ba00a76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/input</value>
      <webElementGuid>6d0fd6c3-f168-44b6-8019-57b899bf30b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'แบบฟอร์มเบิกเงินสดย่อย_/_Petty_Cash_Voucher']</value>
      <webElementGuid>c4749698-0ab3-42d9-a2e7-f91b081ea174</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
