<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_worklist_subject</name>
   <tag></tag>
   <elementGuidId>fef897ae-0dbf-4c90-aa7e-ae471eac6b80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='แบบฟอร์มเบิกเงินสดย่อย_/_Petty_Cash_Voucher']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'แบบฟอร์มเบิกเงินสดย่อย_/_Petty_Cash_Voucher']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d23b92ee-27a2-48f7-9d60-2f1d33aee8cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-filled information-inputTexta-width</value>
      <webElementGuid>ca7cb2e5-bdee-4e8e-880a-6671ddb6b206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>แบบฟอร์มเบิกเงินสดย่อย_/_Petty_Cash_Voucher</value>
      <webElementGuid>f72c6343-3775-4888-998f-020a377decaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>แบบฟอร์มเบิกเงินสดย่อย / Petty Cash Voucher</value>
      <webElementGuid>059c6529-dcbf-4bda-8429-4249284b2b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;แบบฟอร์มเบิกเงินสดย่อย_/_Petty_Cash_Voucher&quot;]</value>
      <webElementGuid>37809eb3-c79b-452f-bbd8-c10c6c247952</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='แบบฟอร์มเบิกเงินสดย่อย_/_Petty_Cash_Voucher']</value>
      <webElementGuid>560ec114-e20a-406f-8b5a-8b182449f8b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[4]/div/div[2]/div/div[3]/div[5]/div[2]/div/span/input</value>
      <webElementGuid>c3996067-cb91-4dc0-a4b3-8ff206b36be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/input</value>
      <webElementGuid>70e1c4ea-edba-4c4b-945c-5b0577e8216e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'แบบฟอร์มเบิกเงินสดย่อย_/_Petty_Cash_Voucher']</value>
      <webElementGuid>e0b461a2-8fe8-422d-b933-c036ff3c1bf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
