<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Department_search-filter-input</name>
   <tag></tag>
   <elementGuidId>eed46ef6-c1ee-4035-a69c-e75c154da83f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.desktop > div.content.filter-content > div.worklist-filter-container > div.all-filter-container > div.Sidebar > div.search-filter-container > div.search-filter-input-component > input.search-filter-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>803d065e-3546-46ec-950b-3c1e3d8164ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8dff2fe6-a5ef-4072-81ea-af9a0d2d1ad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-filter-input</value>
      <webElementGuid>961d1152-405e-443c-8845-f96d15bc396a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>c803f6d9-4aa5-4635-a183-bd699bada666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;main-worklist&quot;]/div[@class=&quot;main-container&quot;]/div[@class=&quot;worklist-container&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;worklist-items-container&quot;]/div[@class=&quot;desktop&quot;]/div[@class=&quot;content filter-content&quot;]/div[@class=&quot;worklist-filter-container&quot;]/div[@class=&quot;all-filter-container&quot;]/div[@class=&quot;Sidebar&quot;]/div[@class=&quot;search-filter-container&quot;]/div[@class=&quot;search-filter-input-component&quot;]/input[@class=&quot;search-filter-input&quot;]</value>
      <webElementGuid>fac3c573-305e-4f32-b2f2-c621eddf875d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[9]</value>
      <webElementGuid>a84d68d1-de63-4594-82d8-fc6b0b15a871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div/div[2]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>7cf9656c-dc6d-4c14-8784-49d4d696379d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>c9d82ed0-f116-4312-8f6b-4485e57e07ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search']</value>
      <webElementGuid>08502760-1e65-4a65-be83-4e825b739aea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
