<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnSubmenuEmployee</name>
   <tag></tag>
   <elementGuidId>639164ce-88c5-4015-aaa1-3c198450b838</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(@id, 'Employee') and contains(@class, 'button-submenu') and (text() = 'Employee' or . = 'Employee')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Employee</value>
      <webElementGuid>a729e73b-5a16-4e02-92f8-11ecb4117e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-submenu</value>
      <webElementGuid>d0adaaa2-5994-4a75-8bf0-a1fc3136ff98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>29767f0c-f359-4f5f-8478-33ae98788840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Employee</value>
      <webElementGuid>040f5095-562f-4ab6-862b-86db95b6c1fa</webElementGuid>
   </webElementProperties>
</WebElementEntity>
