<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnSubMenuDepartment</name>
   <tag></tag>
   <elementGuidId>0ee43980-dc36-48c8-88d6-cc343c2be0b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@href = '/Settings?name=Organization']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fc76b97d-4353-4bea-98cb-bdc248c4ecd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Settings?name=Organization</value>
      <webElementGuid>40137868-4c3a-4c6f-82cb-28ba8b04432c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
