<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Employee header</description>
   <name>ClassrouteSettingsCheck</name>
   <tag></tag>
   <elementGuidId>b0a3d539-5819-4d85-8d95-dfade21fe8fa</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//p[@class = 'route-text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>route-text</value>
      <webElementGuid>ef24c455-5f68-4382-8bec-3ed6e12fce35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c5e918a9-bd17-4a04-94fa-45ed7c103033</webElementGuid>
   </webElementProperties>
</WebElementEntity>
