<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>NewRequest</description>
   <name>Company</name>
   <tag></tag>
   <elementGuidId>c4459449-c218-4ce1-bf1f-ea45cc17d097</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>844cf6eb-6abb-4396-a98b-52a63d894871</webElementGuid>
   </webElementProperties>
</WebElementEntity>
