<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>option a in Type of approval condition form</description>
   <name>DropdownOptionC</name>
   <tag></tag>
   <elementGuidId>0d02a62d-e14d-41a0-91e9-b80098250253</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[(text() = 'c' or . = 'c') and @class = 'ant-select-item-option-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>24b2268e-4a23-4458-9c3b-28fb252f50c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>c</value>
      <webElementGuid>03fbfd2f-0cad-46ca-a5f5-73717ac39b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-item-option-content</value>
      <webElementGuid>b7b1fb13-26b5-4a29-83d0-3e6026edd5b5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
