<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>option a in Type of approval condition form</description>
   <name>DropdownOptionB</name>
   <tag></tag>
   <elementGuidId>14d9f4a7-841a-40d6-bca3-a169364bc575</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[(text() = 'b' or . = 'b') and @class = 'ant-select-item-option-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>454a8b03-d62e-453d-92de-716a6640564f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>647dcb67-1ccf-480a-a156-10222091d1a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-item-option-content</value>
      <webElementGuid>ad9f82d6-75a8-4f25-bf91-dad22db3f12c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
