<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NewRequestfill</name>
   <tag></tag>
   <elementGuidId>42478407-39c8-466f-94df-079c0bb6ab5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@class = 'input-custom' and @id = 'fil']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c15c0fdc-720b-4bc3-902a-5b838079ae04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-custom</value>
      <webElementGuid>79a71453-f8fa-480a-9c9f-9e2f7a6bc7b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fil</value>
      <webElementGuid>e65bbef3-85e2-497b-8c64-1c812a6371ef</webElementGuid>
   </webElementProperties>
</WebElementEntity>
