<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Attachment</name>
   <tag></tag>
   <elementGuidId>313b2054-7f70-4f65-b846-95432873a019</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='Attachment']/div[2])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7f0b35c4-fa4d-4504-8d92-33c8c1ce8b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-col ant-col-offset-1</value>
      <webElementGuid>94bcfd73-ffde-4b0d-9b25-aebb0928b31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Attachment</value>
      <webElementGuid>2f88698c-e48d-4fcc-ad36-d001c9b80105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;request-main-container fade-enter-done&quot;]/div[@class=&quot;request-container&quot;]/div[@class=&quot;inner-content&quot;]/div[@class=&quot;worklist-items-container&quot;]/div[@class=&quot;inner-content show-tablet-navbar-request-max-1024&quot;]/div[@class=&quot;filter-container&quot;]/div[@class=&quot;Sidebar RequestSideBarElement-display-none&quot;]/div[4]/button[@id=&quot;Attachment&quot;]/div[@class=&quot;ant-col ant-col-offset-1&quot;]</value>
      <webElementGuid>19f4fc8f-4892-4610-b62b-ec0f745d1639</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//button[@id='Attachment']/div[2])[2]</value>
      <webElementGuid>48696c8d-0363-44ff-aed0-a9f988055d3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Line Approvals'])[2]/following::div[3]</value>
      <webElementGuid>018b8dab-46bf-47bb-9f27-cc5115112b51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[2]/following::div[6]</value>
      <webElementGuid>f3dc1612-d8b1-4e9f-a58b-470334504403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='History'])[2]/preceding::div[2]</value>
      <webElementGuid>88df21f9-ecd6-4c12-bf05-e4bbb3929c61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[3]/preceding::div[20]</value>
      <webElementGuid>1191ed21-b2af-4e07-82aa-bb7724425369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div[4]/button/div[2]</value>
      <webElementGuid>756e7dfc-cb59-475d-a1ab-f80a7ce4c912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Attachment' or . = 'Attachment')]</value>
      <webElementGuid>d39e86ae-e64a-4785-8de4-39340503c480</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
