<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>body_comment</name>
   <tag></tag>
   <elementGuidId>ecb442db-d684-4eab-af1a-2ec5db4c8460</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='tinymce']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tinymce</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>45fc9c92-d855-49b5-bd2c-7850d8e18fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tinymce</value>
      <webElementGuid>7134b825-6f1b-4c47-975a-d0702935b9bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mce-content-body </value>
      <webElementGuid>1b00f9d8-fc4c-43d6-bbb3-b997adebd71e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>tiny-react_23609281231674732215544</value>
      <webElementGuid>54744533-004c-4634-bd04-c1c8a8852d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Rich Text Area. Press ALT-0 for help.</value>
      <webElementGuid>e36ae48c-da87-46bf-ba21-fd8da5c37d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4afc7aad-4118-45b5-81b8-f5c4727d1da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>98983610-7bd5-45b0-af15-3eb5f6e9b7ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>comment</value>
      <webElementGuid>74108565-4eb5-4cb0-9dd0-d4a19944acfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tinymce&quot;)</value>
      <webElementGuid>10dafe7f-c51e-4ac3-ac96-1df28f1f5a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_WOLF/iframe_concat(id(, , tiny-react_23609281231_ee1545</value>
      <webElementGuid>edd8510f-8729-4788-af8b-9016b8a0d0d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//body[@id='tinymce']</value>
      <webElementGuid>64b066f7-9c4e-4944-927e-c36351d6e496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body</value>
      <webElementGuid>3ba5669f-2c78-44b0-a932-de5ced9d6853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//body[@id = 'tinymce' and (text() = 'comment' or . = 'comment')]</value>
      <webElementGuid>264b9a35-eebe-4eea-8e9c-3a95b41c7b04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
