<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_KTL-VLD01-2023-00000126 Jan 2023 , 1142_b0ba86</name>
   <tag></tag>
   <elementGuidId>cd22d635-d1c3-4283-a6bf-e0c048aa9f70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div/div/div[2]/div/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>69ac52b4-0f3f-47fc-87c2-2ab2921f77a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-container </value>
      <webElementGuid>3aac9d3e-8120-4c19-8812-8385eaa35bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KTL-VLD01-2023-00000126 Jan 2023 , 11:42Test Validation By KatalonKTL-VLD01: Validation FormDraftRequest Byวูล์ฟWaiting forวูล์ฟKTL-VLD01-2023-000001Test Validation By KatalonKTL-VLD01: Validation FormDraftRequest byวูล์ฟWaiting forวูล์ฟ</value>
      <webElementGuid>13f481ff-5ca8-43ef-ae8d-8e7312b971b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;main-worklist&quot;]/div[@class=&quot;main-container&quot;]/div[@class=&quot;worklist-container&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;worklist-items-container&quot;]/div[@class=&quot;worklist-cards-container&quot;]/div[@class=&quot;cards-container&quot;]/div[@class=&quot;card-container&quot;]</value>
      <webElementGuid>5ac13950-9fc5-41b6-914b-bd928bf7c9dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div/div[2]/div/div/div[2]/div</value>
      <webElementGuid>81671b49-017d-4266-9e33-c5d6c7882f71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='items per page'])[1]/following::div[2]</value>
      <webElementGuid>f68b7f95-f359-44c4-a45c-48abe250aaf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show'])[1]/following::div[5]</value>
      <webElementGuid>e592e4dc-65d0-4bf6-977b-6a416a29d96b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div</value>
      <webElementGuid>e4b943cf-de07-43d8-ab27-efb0e617f009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'KTL-VLD01-2023-00000126 Jan 2023 , 11:42Test Validation By KatalonKTL-VLD01: Validation FormDraftRequest Byวูล์ฟWaiting forวูล์ฟKTL-VLD01-2023-000001Test Validation By KatalonKTL-VLD01: Validation FormDraftRequest byวูล์ฟWaiting forวูล์ฟ' or . = 'KTL-VLD01-2023-00000126 Jan 2023 , 11:42Test Validation By KatalonKTL-VLD01: Validation FormDraftRequest Byวูล์ฟWaiting forวูล์ฟKTL-VLD01-2023-000001Test Validation By KatalonKTL-VLD01: Validation FormDraftRequest byวูล์ฟWaiting forวูล์ฟ')]</value>
      <webElementGuid>00276948-3641-4dfe-83d8-e6927884dbc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
