<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_TCB</name>
   <tag></tag>
   <elementGuidId>192c4097-5d8a-49d4-af63-29018ebf1342</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pr_id_7_content']/div/div/table/tbody/tr/td/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'TCB' or . = 'TCB')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.tooltip-data</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0fdea458-1ca5-448a-8a18-c142d2c42739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tooltip-data</value>
      <webElementGuid>e71b337e-5d11-4462-bb2d-da16ab4d554b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pr-tooltip</name>
      <type>Main</type>
      <value>EmployeeId : undefined</value>
      <webElementGuid>55d0cbd2-2f54-4da6-8b40-65c300f9aa8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TCB</value>
      <webElementGuid>abf1166b-8862-4ea8-8456-9db170928c40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_7_content&quot;)/div[@class=&quot;p-datatable p-component p-datatable-selectable p-datatable-responsive-scroll&quot;]/div[@class=&quot;p-datatable-wrapper&quot;]/table[@class=&quot;p-datatable-table&quot;]/tbody[@class=&quot;p-datatable-tbody&quot;]/tr[@class=&quot;p-selectable-row&quot;]/td[1]/div[@class=&quot;tooltip-data&quot;]</value>
      <webElementGuid>ac8141a2-1d7f-4682-a4cb-881856eec74e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_7_content']/div/div/table/tbody/tr/td/div</value>
      <webElementGuid>fa2892ba-43ad-4c7d-86fc-781e6f03cf0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload'])[1]/following::div[38]</value>
      <webElementGuid>6e5392a0-5fab-49d4-bb04-d7870079ec18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='attachment'])[1]/following::div[43]</value>
      <webElementGuid>124b3c69-dc76-4aff-9634-e022b06c70a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TechCons Biz Co.,Ltd. (Head Office)'])[1]/preceding::div[1]</value>
      <webElementGuid>2a330428-8586-4e92-9fdb-3a018ad7ead0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div</value>
      <webElementGuid>69b2ebe0-c197-41fc-8d0b-284f0fa4a75b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'TCB' or . = 'TCB')]</value>
      <webElementGuid>47ba312d-775a-4c82-b7bd-0b3d7909b185</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
