<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_InformationTest Reference FormNew Reque_f5de58</name>
   <tag></tag>
   <elementGuidId>92af75d1-e8d7-41cd-9136-0c58a72dcd59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div/div[4]/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.request-container-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>316e54f7-f4df-413b-ae8f-acb92625aaeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>request-container-item</value>
      <webElementGuid>c7e92c3f-65da-43ef-8d88-2d449470d76b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>InformationTest Reference FormNew RequestAuto GenerateRequest Dateวันที่ร้องขอเอกสาร26 Jan 2023Company *บริษัท Toเรียน CC :สำเนา Subject *เรื่องReference Templateเอกสารอ้างอิงAdd#รถForm Templateชื่อเอกสารSubjectหัวข้อเอกสารNo available optionsTest Reference Form By Katalon รถ ที่ต้องการจอง--select--ต้องการคนขับรถ โปรดระบุต้องการไม่ต้องการวันที่เริ่มต้น เวลาเริ่มต้น วันที่สิ้นสุด เวลาสิ้นสุด Other information Fullname attachment Upload</value>
      <webElementGuid>a2a4a0fa-145b-439a-831c-c772f1ee75d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;request-main-container fade-enter-done&quot;]/div[@class=&quot;request-container&quot;]/div[@class=&quot;inner-content&quot;]/div[@class=&quot;worklist-items-container&quot;]/div[@class=&quot;request-container-item&quot;]</value>
      <webElementGuid>d4394a2b-c336-44d1-873a-7672f1db0054</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[4]/div/div[2]</value>
      <webElementGuid>eaefcb2b-6c7c-4a69-a2dd-1b85f32294d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attachment'])[2]/following::div[14]</value>
      <webElementGuid>22235f82-baa0-4014-a969-6acc264b6c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Line Approvals'])[2]/following::div[17]</value>
      <webElementGuid>8f7b9bc9-7b67-4aac-8e5a-e82fd2ecc2b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]</value>
      <webElementGuid>b42d83af-6d15-4afa-b199-9b908b1f93d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'InformationTest Reference FormNew RequestAuto GenerateRequest Dateวันที่ร้องขอเอกสาร26 Jan 2023Company *บริษัท Toเรียน CC :สำเนา Subject *เรื่องReference Templateเอกสารอ้างอิงAdd#รถForm Templateชื่อเอกสารSubjectหัวข้อเอกสารNo available optionsTest Reference Form By Katalon รถ ที่ต้องการจอง--select--ต้องการคนขับรถ โปรดระบุต้องการไม่ต้องการวันที่เริ่มต้น เวลาเริ่มต้น วันที่สิ้นสุด เวลาสิ้นสุด Other information Fullname attachment Upload' or . = 'InformationTest Reference FormNew RequestAuto GenerateRequest Dateวันที่ร้องขอเอกสาร26 Jan 2023Company *บริษัท Toเรียน CC :สำเนา Subject *เรื่องReference Templateเอกสารอ้างอิงAdd#รถForm Templateชื่อเอกสารSubjectหัวข้อเอกสารNo available optionsTest Reference Form By Katalon รถ ที่ต้องการจอง--select--ต้องการคนขับรถ โปรดระบุต้องการไม่ต้องการวันที่เริ่มต้น เวลาเริ่มต้น วันที่สิ้นสุด เวลาสิ้นสุด Other information Fullname attachment Upload')]</value>
      <webElementGuid>f20c8845-22c4-4ea0-87f1-843c5bc1bacc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
