<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>3c357177-fde9-448e-8284-95613d1b7580</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='basic']/div[2]/div[4]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ant-space.ant-space-vertical</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>974edec7-08e3-46d4-92df-474af5ce23e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-space ant-space-vertical</value>
      <webElementGuid>4fe537b7-c671-4041-8abe-198b92e4f7c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ต้องการไม่ต้องการ</value>
      <webElementGuid>a3796bd3-1846-4bcf-b17b-aaaee575f400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic&quot;)/div[@class=&quot;set-padding-core-control row&quot;]/div[@class=&quot;padding-controller col-xl-4 col-md-4 col-sm-12 col-12&quot;]/div[@class=&quot;input-component-container&quot;]/div[@class=&quot;ant-radio-group ant-radio-group-outline ant-radio-group-large&quot;]/div[@class=&quot;ant-space ant-space-vertical&quot;]</value>
      <webElementGuid>cdb27453-d532-4b8d-91ad-187a37f63144</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div[2]/div[4]/div/div/div</value>
      <webElementGuid>ff6d92ee-05ba-4555-9110-c8880de2af98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ต้องการคนขับรถ'])[1]/following::div[4]</value>
      <webElementGuid>1433660c-0751-48d5-ae96-8374cfbb7d91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--select--'])[1]/following::div[6]</value>
      <webElementGuid>90dbe7ea-aee1-449c-8b81-6c0372d8d212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div/div/div</value>
      <webElementGuid>3dca2579-ef0a-4b04-a815-cb756c8333c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'ต้องการไม่ต้องการ' or . = 'ต้องการไม่ต้องการ')]</value>
      <webElementGuid>f5ed3f57-0842-4047-a932-fabf1f1a6cc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
