<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_12Email Address Password Forgot Passwor_d98aab</name>
   <tag></tag>
   <elementGuidId>5c6b1be1-e8aa-4ac0-a08e-4c6e3f6745de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.login-screens</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fc841fc4-597d-4af1-b091-21a77b130cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-screens</value>
      <webElementGuid>545ad12d-92dd-4c59-af7d-4fce76f44df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12Email Address :Password :Forgot Password? | RegisterSign In</value>
      <webElementGuid>158de6be-4236-46cd-9e71-270d0d1f35d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;login-screens&quot;]</value>
      <webElementGuid>3b442346-bb98-43b2-b4b8-cd4616abfc07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div</value>
      <webElementGuid>40c97089-43ad-4ae3-9a4d-f82245094945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div</value>
      <webElementGuid>db0d58a8-db00-46bc-96ef-af4c0030bc81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '12Email Address :Password :Forgot Password? | RegisterSign In' or . = '12Email Address :Password :Forgot Password? | RegisterSign In')]</value>
      <webElementGuid>42f36e90-34ec-4a0f-b083-d690bba9e9c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
