<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Honda CR-V (  6502)_p-radiobutton-box p_82aa2b</name>
   <tag></tag>
   <elementGuidId>30460e28-3131-437b-9a31-a04c5e92da6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pr_id_13_content']/div/div/table/tbody/tr/td/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.p-radiobutton-box.p-component</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>10f15cef-2c11-4847-aa08-21344f666aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-radiobutton-box p-component</value>
      <webElementGuid>71a4cba4-7ca3-4442-a43d-620b5d139b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>d10e0a8e-54b3-43ad-9776-02316e78c9ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>88fcc7a3-6148-4e64-a9d2-52d23f07fe22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_13_content&quot;)/div[@class=&quot;p-datatable p-component p-datatable-selectable p-datatable-responsive-scroll&quot;]/div[@class=&quot;p-datatable-wrapper&quot;]/table[@class=&quot;p-datatable-table&quot;]/tbody[@class=&quot;p-datatable-tbody&quot;]/tr[@class=&quot;p-selectable-row&quot;]/td[@class=&quot;p-selection-column&quot;]/div[@class=&quot;p-radiobutton p-component&quot;]/div[@class=&quot;p-radiobutton-box p-component&quot;]</value>
      <webElementGuid>06a8f43b-a07e-460b-8a63-e04392c5ebb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_13_content']/div/div/table/tbody/tr/td/div/div[2]</value>
      <webElementGuid>cbff0dc7-8ec3-47e3-82d5-c3c30ef92c6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Honda CR-V (ทะเบียน พย 6502)'])[1]/following::div[19]</value>
      <webElementGuid>0eb3eac3-a689-4bf8-aed5-9dc898d259ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Honda Civic (ทะเบียน ชจ 701)'])[1]/following::div[21]</value>
      <webElementGuid>510c0895-b584-4146-95ac-77a250612d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Honda City (ทะเบียน จว 4103)'])[2]/preceding::div[2]</value>
      <webElementGuid>e68d733c-20e2-4aeb-894e-c12974ba5a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Direct to Position'])[1]/preceding::div[2]</value>
      <webElementGuid>832a80bf-e886-4c6a-80f0-7e9923d08dba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div[2]</value>
      <webElementGuid>64f8056e-1732-457f-96f5-dc2b7cd9f39f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
