<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_New RequestNew RequestWorklist  To Do L_019f99</name>
   <tag></tag>
   <elementGuidId>f59fd262-ea8e-4403-879d-5a1e568d942c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.header-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8d682879-0e3f-4392-8e9a-342a5094d9cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-container</value>
      <webElementGuid>245da18c-9674-45a7-b79f-2ffcdd5434ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New RequestNew RequestWorklist / To Do List (134)</value>
      <webElementGuid>ed97234f-36c7-46d8-9cd4-ef1407b55355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;main-worklist&quot;]/div[@class=&quot;main-container&quot;]/div[@class=&quot;worklist-container&quot;]/div[@class=&quot;header-container&quot;]</value>
      <webElementGuid>0ee339df-b0b4-4f7e-9bd4-3c886ca5ff13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div/div</value>
      <webElementGuid>7fe30211-7b2e-40de-994a-2f5c5ecb48b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show'])[1]/preceding::div[4]</value>
      <webElementGuid>98c2157d-1fbb-468e-a001-2fae2cf149c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='items per page'])[1]/preceding::div[7]</value>
      <webElementGuid>27ae91a2-e73f-4532-9e50-ed8e743ff6d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div</value>
      <webElementGuid>73e99dbc-31d4-4855-98d8-c7cc1c7acaa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'New RequestNew RequestWorklist / To Do List (134)' or . = 'New RequestNew RequestWorklist / To Do List (134)')]</value>
      <webElementGuid>21365349-2fca-4b86-893c-9f47b698e3cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
