<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__padding-controller col-xl-4 col-md-4 c_16246f</name>
   <tag></tag>
   <elementGuidId>9a177aea-d616-40f1-b45e-022ce191ae45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='basic']/div[3]/div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d36b13f1-8510-467d-b703-7796f4ffe761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>padding-controller col-xl-4 col-md-4 col-sm-12 col-12</value>
      <webElementGuid>176221fe-4fa0-4656-b15a-eb3e0e4b618c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic&quot;)/div[@class=&quot;set-padding-core-control row&quot;]/div[@class=&quot;padding-controller col-xl-4 col-md-4 col-sm-12 col-12&quot;]</value>
      <webElementGuid>4fcdc35b-ac28-41f8-bc95-bb71ee8a1e98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div[3]/div[4]</value>
      <webElementGuid>196e15ee-cb52-4667-ab64-bab36d8d98e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='จำนวนเงิน'])[1]/following::div[1]</value>
      <webElementGuid>f6ffca32-ce14-4d92-8939-c85a4a41a8ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Data'])[1]/following::div[11]</value>
      <webElementGuid>48a93dd8-1cda-45b4-91e5-0984e934eca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='เพิ่ม VAT'])[1]/preceding::div[10]</value>
      <webElementGuid>e0fb3f73-34cd-4b4e-b4a7-71e7b37c3721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='รวม'])[1]/preceding::div[23]</value>
      <webElementGuid>7ed1abf5-f4bd-459a-a172-6f345aab970e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[3]/div[4]</value>
      <webElementGuid>134cad73-0d21-47d3-9634-f1f12b8b0878</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
