<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Email Address Password Forgot Password _fe4803</name>
   <tag></tag>
   <elementGuidId>6246a85e-4d1f-40cc-8958-e16d455243d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.right-card-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/form/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bf9231ed-b4f2-4cc6-8dff-41116286ee78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>right-card-container</value>
      <webElementGuid>f5fa88a4-7240-4968-8581-fa1e90c52834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email Address :กรุณากรอกชื่อบัญชีPassword :Forgot Password? | RegisterSign In</value>
      <webElementGuid>305222f4-bba0-46ed-9d7b-5738baafb483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;login-screens&quot;]/div[@class=&quot;login-container&quot;]/form[1]/div[@class=&quot;right-card-container&quot;]</value>
      <webElementGuid>810b67cf-37b2-41c9-bdaa-03f2052648cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/form/div</value>
      <webElementGuid>c4c86021-56f0-4af9-9375-1cc2faba8f8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div</value>
      <webElementGuid>c535dd66-da39-4ca1-bfef-1da2da4992fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Email Address :กรุณากรอกชื่อบัญชีPassword :Forgot Password? | RegisterSign In' or . = 'Email Address :กรุณากรอกชื่อบัญชีPassword :Forgot Password? | RegisterSign In')]</value>
      <webElementGuid>38ce9d2f-1c95-4079-a85e-ccf7e240fa3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
