<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Email Address Password Forgot Password_8e5946_1</name>
   <tag></tag>
   <elementGuidId>ed639b80-4ebe-4c4b-a7e7-d153a671fcbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>65ab8e5a-c89e-4224-9662-054f112b3e81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email Address :Password :Forgot Password? | RegisterSign In</value>
      <webElementGuid>29bc1376-5861-4f8b-a1ac-49096f5d4ef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;login-screens&quot;]/div[@class=&quot;login-container&quot;]/form[1]</value>
      <webElementGuid>90b962aa-4cbe-4fb6-af04-abb14f68c64b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/form</value>
      <webElementGuid>c3ce6b0c-a01f-442e-8d58-218893d4d563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>23a0d48c-2363-40a3-8640-8bb3abd2b6ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[(text() = 'Email Address :Password :Forgot Password? | RegisterSign In' or . = 'Email Address :Password :Forgot Password? | RegisterSign In')]</value>
      <webElementGuid>b34116cc-7cc7-4c53-938d-60e07e13b5a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
