<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_total_add_bt</name>
   <tag></tag>
   <elementGuidId>0f233b2e-0a81-4985-92e6-68df6d415d92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='add_bt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#add_bt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>fd936ffe-2b2c-4c9e-9b0e-6920b0557764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pi pi-plus</value>
      <webElementGuid>90190735-7756-4a57-968e-a57f771dac38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add_bt</value>
      <webElementGuid>3844d09b-4950-4e45-919a-e18b15237d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add_bt&quot;)</value>
      <webElementGuid>2e43fe0d-ab30-4735-aa7e-7a9870977261</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='add_bt']</value>
      <webElementGuid>a6965494-2087-4dcb-a39a-1d658cc0829d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='table-control']/div/div/table/thead/tr/th[6]/i</value>
      <webElementGuid>ecb4d7b9-ce9d-4660-98b7-6c353db8ff22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>e05648ea-eeeb-4ead-a010-98ac506203ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'add_bt']</value>
      <webElementGuid>2f9792bb-6902-4195-9aab-d48a8375e0e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
