<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_total_pi pi-plus</name>
   <tag></tag>
   <elementGuidId>409c1770-9564-4fc6-a5bf-06add5827b9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='table-control']/div/div/table/thead/tr/th[6]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.pi.pi-plus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>267029a1-6899-4c4b-af66-c1650b548714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pi pi-plus</value>
      <webElementGuid>1aee71df-d178-475e-a79f-923289b9f295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-control&quot;)/div[@class=&quot;ant-table-container&quot;]/div[@class=&quot;ant-table-header&quot;]/table[1]/thead[@class=&quot;ant-table-thead&quot;]/tr[1]/th[@class=&quot;ant-table-cell action-column ant-table-cell-fix-right ant-table-cell-fix-right-first&quot;]/i[@class=&quot;pi pi-plus&quot;]</value>
      <webElementGuid>3d824bb6-9fe1-482d-b010-a471750e6809</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='table-control']/div/div/table/thead/tr/th[6]/i</value>
      <webElementGuid>d3645b73-3734-4c26-bb55-f93545572a08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>447c037d-2e2d-44e4-9547-18def6a0217c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
