<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , tiny-react_26058033121_3be4ff</name>
   <tag></tag>
   <elementGuidId>fb4ca567-034e-4e64-921f-1e8645621eaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tiny-react_26058033121674819798038_ifr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='tiny-react_26058033121674819798038_ifr']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>9deb23ae-29f0-43c9-8f2a-7d873b1bf36d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tiny-react_26058033121674819798038_ifr</value>
      <webElementGuid>576def53-86d3-419f-a526-c4c4256e248d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>af3fc47c-de0a-4754-935b-e7f6de5167b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bd4073f5-310c-4b41-9beb-be90b0c135d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Rich Text Area</value>
      <webElementGuid>af2563d5-f670-476a-98ea-d4d0129b4f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tox-edit-area__iframe</value>
      <webElementGuid>b779d5db-63a4-4839-987e-96caee5f47b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tiny-react_26058033121674819798038_ifr&quot;)</value>
      <webElementGuid>73d42822-adb1-4c1b-b9c6-8fb00cf77fcf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='tiny-react_26058033121674819798038_ifr']</value>
      <webElementGuid>c9ea78fb-871d-40fc-817d-80e4f1f0c43c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_13_content']/div[2]/div/div/div[2]/div/iframe</value>
      <webElementGuid>a7a907f9-0e8b-4b0c-a936-73a41b3c72fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>11f0cc0f-b3e5-417b-8d98-cdf961a3069c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'tiny-react_26058033121674819798038_ifr' and @title = 'Rich Text Area']</value>
      <webElementGuid>942be95f-03a2-466b-ab8f-c3549b9c2382</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
