<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , tiny-react_61524422521_468cfa</name>
   <tag></tag>
   <elementGuidId>5dbe3cd2-70b3-4588-92ac-9b2fce8016e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tiny-react_61524422521674819209678_ifr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='tiny-react_61524422521674819209678_ifr']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>3b2e1d40-6242-4cc5-b5b9-04c53df7b0c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tiny-react_61524422521674819209678_ifr</value>
      <webElementGuid>b09f009d-cf72-4fa5-a49a-46039123859c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>43beb7ac-1f60-41ae-b8f6-ff26cbaa0777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c195383e-b146-4e68-a011-2c08058aeb21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Rich Text Area</value>
      <webElementGuid>0244f02e-4e1e-4333-a842-f86214e930c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tox-edit-area__iframe</value>
      <webElementGuid>3f32a073-d2db-49eb-9cf0-7be6aedf3222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tiny-react_61524422521674819209678_ifr&quot;)</value>
      <webElementGuid>7a6b7030-71a8-44b7-8f5e-161487a1aa05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='tiny-react_61524422521674819209678_ifr']</value>
      <webElementGuid>52d85602-7e0c-4ab4-86ad-896a8e0740d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_13_content']/div[2]/div/div/div[2]/div/iframe</value>
      <webElementGuid>90ca3233-d82d-4e00-b781-1706f6b41884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>710c8613-eebc-46fe-b443-92167c7d0c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'tiny-react_61524422521674819209678_ifr' and @title = 'Rich Text Area']</value>
      <webElementGuid>3ae99084-babc-4c8a-babb-bbd7e5ed7f07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
