<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , tiny-react_28909096221_6e2f71</name>
   <tag></tag>
   <elementGuidId>15170e0a-9607-43f6-b573-c9e58362fb0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tiny-react_28909096221674925451442_ifr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='tiny-react_28909096221674925451442_ifr']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>298e4bb8-9748-4921-a221-9b806dbab925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tiny-react_28909096221674925451442_ifr</value>
      <webElementGuid>9d4d42e3-a8b3-4a9a-a72f-8cf111b682d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4d5e887f-bdd5-4e24-8f03-4f4e3a176888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0c51f024-41dc-4902-9e4f-82a255687b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Rich Text Area</value>
      <webElementGuid>2fa466fd-ab2b-4781-a026-3a0fcf397e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tox-edit-area__iframe</value>
      <webElementGuid>d2913150-9c6f-4e14-b133-1ac4e49e5c9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tiny-react_28909096221674925451442_ifr&quot;)</value>
      <webElementGuid>46c34d1c-23e7-4805-9d97-0f967532cdf7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='tiny-react_28909096221674925451442_ifr']</value>
      <webElementGuid>2523a6d2-dca7-4918-8fb7-4c5e4dfe3ac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_13_content']/div[2]/div/div/div[2]/div/iframe</value>
      <webElementGuid>09bb4179-a114-4fa4-8dd2-a44885de6db0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>377f38ef-c940-403d-bfde-50021ebe6603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'tiny-react_28909096221674925451442_ifr' and @title = 'Rich Text Area']</value>
      <webElementGuid>3e794e0a-7690-45fd-8727-3710a1d92afa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
