<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , tiny-react_74674481041_812acd</name>
   <tag></tag>
   <elementGuidId>b0ae47cc-b265-4d5b-b173-7cf2c883d18b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='tiny-react_74674481041674732269317_ifr']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tiny-react_74674481041674732269317_ifr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>9eb70fb5-4c28-4d10-b7bf-26c2c368c35c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tiny-react_74674481041674732269317_ifr</value>
      <webElementGuid>eba6dad7-4c63-4c93-8648-cfb01ba5204d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e448de80-2305-47b3-8ddd-f1ac138c67df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9b81ca01-3151-4e48-87ac-6fbb20d35b50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Rich Text Area</value>
      <webElementGuid>62355831-cc60-4bc7-be3a-39d8fbcccd8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tox-edit-area__iframe</value>
      <webElementGuid>0fc368b8-4f63-4f9b-afcf-507fd60a725c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tiny-react_74674481041674732269317_ifr&quot;)</value>
      <webElementGuid>94942941-a58e-41f3-ba0b-e21fc384bd88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='tiny-react_74674481041674732269317_ifr']</value>
      <webElementGuid>e82cde43-acc6-4ffd-8f20-8021f1c84ba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_33_content']/div[2]/div/div/div[2]/div/iframe</value>
      <webElementGuid>99ba57d0-8fb3-45f3-b85f-24d01b200c44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>ad7dd36a-2a69-4483-b6f7-8405a90ca7d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'tiny-react_74674481041674732269317_ifr' and @title = 'Rich Text Area']</value>
      <webElementGuid>d0e018b5-4466-49a9-8daa-65b3759faf9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
