<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , tiny-react_27928637621_6ec38d</name>
   <tag></tag>
   <elementGuidId>762efcb7-c56c-4256-a4ef-28df978ebebc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tiny-react_27928637621674928711002_ifr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='tiny-react_27928637621674928711002_ifr']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>f5e782b7-518b-4c3b-ae82-a21a01b98e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tiny-react_27928637621674928711002_ifr</value>
      <webElementGuid>7b66ef4c-9beb-4367-b5a3-2c395539fe7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9d0291be-7456-4d6a-9b7b-894d26aef7e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>688435c3-367b-4789-816d-87398693c39a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Rich Text Area</value>
      <webElementGuid>78965847-a5e4-47f6-a43e-319ee1667dba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tox-edit-area__iframe</value>
      <webElementGuid>621bcf6f-81fd-4265-84b0-c2be8ab393e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tiny-react_27928637621674928711002_ifr&quot;)</value>
      <webElementGuid>8b31d44d-28e2-4c08-84c9-a1920a659eed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='tiny-react_27928637621674928711002_ifr']</value>
      <webElementGuid>ef6d1599-2613-4f55-8a1d-01a8acfe740e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_13_content']/div[2]/div/div/div[2]/div/iframe</value>
      <webElementGuid>90a3b109-6373-4401-a1ee-43e9198f8901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>3ececcb9-cc70-4af8-92c9-156791f2a68c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'tiny-react_27928637621674928711002_ifr' and @title = 'Rich Text Area']</value>
      <webElementGuid>95225841-7317-413a-a864-0b8b09355e71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
