<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , tiny-react_14758489321_adf401</name>
   <tag></tag>
   <elementGuidId>6fdb722e-7cf3-48b3-9e23-e8007d7dff23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='tiny-react_14758489321674729068763_ifr']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tiny-react_14758489321674729068763_ifr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>43131ab9-1864-442b-be2a-d07d6cf1ed13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tiny-react_14758489321674729068763_ifr</value>
      <webElementGuid>14d0c76d-2222-491a-849d-e02d90b919b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d0c9b195-d1b1-4ae2-bbfd-a09a4a1036d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0f0e7152-5f7e-49a6-8fe6-2230090214ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Rich Text Area</value>
      <webElementGuid>c0cec238-aa82-4928-af14-4808c5136258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tox-edit-area__iframe</value>
      <webElementGuid>c7a76d0f-994c-4692-bd7a-061f77788569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tiny-react_14758489321674729068763_ifr&quot;)</value>
      <webElementGuid>c9e882ba-6de4-4fec-b477-2facab8afe8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='tiny-react_14758489321674729068763_ifr']</value>
      <webElementGuid>e08346df-cbc3-42b3-aa35-de037c441814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_14_content']/div[2]/div/div/div[2]/div/iframe</value>
      <webElementGuid>c1b308f2-5915-498e-a345-5c871da4ff7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>d6d3be2c-c8d4-412d-a7de-9b218db720f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'tiny-react_14758489321674729068763_ifr' and @title = 'Rich Text Area']</value>
      <webElementGuid>8be2082c-0c7a-4d2b-96b1-940c0009db88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
