<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Requestor_img-logo</name>
   <tag></tag>
   <elementGuidId>4c5d5624-1e8c-4193-a50d-a3dd5814bc46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img-logo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>38cddcf3-4904-4ea6-90b2-fa3e7dcaa3e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-logo</value>
      <webElementGuid>6cf70016-e1fd-4793-a7da-3b3d4069cdcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://qar2.wolfapprove.com//Images/Logo/25650325164009_wolfLogo.png</value>
      <webElementGuid>9364685a-0e86-4847-995f-a6195ce26ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>71b43a16-d3bd-4c50-83c4-00657b5a46bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;navbar-container -active&quot;]/div[@class=&quot;logo-container desktop&quot;]/img[@class=&quot;img-logo&quot;]</value>
      <webElementGuid>0c8c984b-9425-45ff-b68d-3cd4a7181241</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/img</value>
      <webElementGuid>4f05be5c-0832-4580-be63-37ef535014ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='logo']</value>
      <webElementGuid>16121c94-42d2-44aa-adf5-0dc6add3b879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>6e6c2c13-8236-45b1-b9ce-2984ce88cf21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://qar2.wolfapprove.com//Images/Logo/25650325164009_wolfLogo.png' and @alt = 'logo']</value>
      <webElementGuid>dfbb512c-c37e-4ea5-b1b0-494e6356c3c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
