<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Related List_img-logo</name>
   <tag></tag>
   <elementGuidId>a68013bc-8643-467a-bc4e-e7a107d0b85e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-logo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>284aa49d-f02f-4e27-af6a-f6e7a1e13b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-logo</value>
      <webElementGuid>03698448-c075-4604-9eb2-98652ad2a6f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://qar2.wolfapprove.com//Images/Logo/25650325164009_wolfLogo.png</value>
      <webElementGuid>a5264d14-e455-4c14-93a4-b4739cc4f270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>120e0207-173c-4fb5-aa45-a84ecc24035e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;navbar-container -active&quot;]/div[@class=&quot;logo-container desktop&quot;]/img[@class=&quot;img-logo&quot;]</value>
      <webElementGuid>e3263048-3037-4337-930d-b0ebcf865c5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/img</value>
      <webElementGuid>e718af62-f23a-4155-8bb5-ad9baadb067f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='logo']</value>
      <webElementGuid>1c5a0357-05a2-4c7c-9676-c5d66c19120e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>e23ec010-46c2-4aba-9c13-ed01c58399be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://qar2.wolfapprove.com//Images/Logo/25650325164009_wolfLogo.png' and @alt = 'logo']</value>
      <webElementGuid>3111b724-e0b4-4be5-a3a6-f8badf91d144</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
