<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Requestor_img-logo</name>
   <tag></tag>
   <elementGuidId>4c5d5624-1e8c-4193-a50d-a3dd5814bc46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-logo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>077ccf65-b588-41fb-beb3-9c7e902c7200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-logo</value>
      <webElementGuid>7e063aeb-6cb2-4b54-bf4b-45fadd88a320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://qar2.wolfapprove.com//Images/Logo/25650325164009_wolfLogo.png</value>
      <webElementGuid>439e3bff-33d4-41ce-a3e5-d011490b4c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>50611de2-2b7e-4492-b830-24de0ed2a40b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;navbar-container -active&quot;]/div[@class=&quot;logo-container desktop&quot;]/img[@class=&quot;img-logo&quot;]</value>
      <webElementGuid>54408e8b-e1ae-48a2-8df9-f3620f3e8e60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/img</value>
      <webElementGuid>9b6b115c-5e85-4e06-87fa-d917bb1019b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='logo']</value>
      <webElementGuid>0581fe3b-9439-443d-a108-464ea344f8fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>f5590b16-afce-41dc-a0cd-0fe685e102db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://qar2.wolfapprove.com//Images/Logo/25650325164009_wolfLogo.png' and @alt = 'logo']</value>
      <webElementGuid>9440600c-b9ae-4cc1-9f31-a80c4bb9e15e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
