<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm_p-inputtext p-component set-i_867df8</name>
   <tag></tag>
   <elementGuidId>942f281f-024f-43cb-8d63-4f144c01ce50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.p-inputtext.p-component.set-input-search-dialog</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6be64ba3-f0f1-4ec5-ac73-15b776e9281b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component set-input-search-dialog</value>
      <webElementGuid>75cb0b93-0634-4bf4-b9c1-2daf894e894d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>23a4aec8-c3cd-4871-98a9-093488fdf2e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_14_header&quot;)/div[@class=&quot;p-d-flex p-jc-end&quot;]/span[@class=&quot;p-input-icon-left set-span-search-dialog&quot;]/input[@class=&quot;p-inputtext p-component set-input-search-dialog&quot;]</value>
      <webElementGuid>0f280613-2b10-4685-8ebf-304dcc772551</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
      <webElementGuid>3574e4bf-7fc8-4158-a435-9611a88eaa79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_14_header']/div/span/input</value>
      <webElementGuid>cef347dd-89ec-4659-aa9c-90ee7a94ce31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/span/input</value>
      <webElementGuid>c17f6d74-7eeb-417f-8093-756112c316c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search']</value>
      <webElementGuid>faeb3a4f-bc42-4c06-a004-6720dea77fa2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
