<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_total_0_0_price</name>
   <tag></tag>
   <elementGuidId>52042f2e-4766-4a29-af37-7fae5063d5e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='0_0_price']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#0_0_price</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>72d1f796-3a2a-44af-aed7-8850ae3d586e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>dca65309-16d0-41d4-b0f7-3a9872abf119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>spinbutton</value>
      <webElementGuid>1750ad7c-960c-44f2-aebb-ca9210430424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuenow</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bf797fd5-9d10-4389-a7d5-f291e8694f72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>30aacb46-467c-458e-8541-d873141214d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>0_0_price</value>
      <webElementGuid>b84fdae7-6ba6-46a2-b62b-31d603f2e44d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input-number-input</value>
      <webElementGuid>457c6475-eec7-43e7-8b67-c9ec2b928f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>3b0bd55f-a846-4d56-ac1f-ee78492cef96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;0_0_price&quot;)</value>
      <webElementGuid>015ba11b-c8fc-41e3-bfd1-3c8ca61aea7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='0_0_price']</value>
      <webElementGuid>7a7183d5-59a1-47bd-97a1-085b5e4ec744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='table-control']/div/div[2]/table/tbody/tr[2]/td[2]/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>9b30fac1-f093-4afa-b417-2c3230999fcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>6b069973-141f-4c06-995d-b9ad7dabe578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '0_0_price']</value>
      <webElementGuid>fba827e4-2266-4c63-b4ec-d0e38b7ca39c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
