<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__items2.layout1.data.value</name>
   <tag></tag>
   <elementGuidId>5f4c2097-f6a9-4f69-b233-fc4cadd38588</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='items[2].layout[1].data.value']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;items[2].layout[1].data.value&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>36220b06-e501-4da9-a8a1-e90ea3ce0f2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>items[2].layout[1].data.value</value>
      <webElementGuid>41dd1595-51c5-4fc8-bdba-2969703525a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-lg input-component</value>
      <webElementGuid>e5e431b0-4b7b-4b9b-b5ce-5b87b38eb848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>เช่น 08:30 น.</value>
      <webElementGuid>3447fbfa-fcbc-4b41-bb10-3ab0bea922d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>42504928-6bc1-460b-b9d3-583fce2a90bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic&quot;)/div[@class=&quot;set-padding-core-control row&quot;]/div[@class=&quot;padding-controller col-xl-4 col-md-4 col-sm-12 col-12&quot;]/div[@class=&quot;input-component-container&quot;]/input[@class=&quot;ant-input ant-input-lg input-component&quot;]</value>
      <webElementGuid>d87ba534-9b58-4e34-8cd7-0636deb880cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='items[2].layout[1].data.value']</value>
      <webElementGuid>d28b8bf6-c103-4a9b-b7ea-4ee2ee86a27e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div[3]/div[4]/div/input</value>
      <webElementGuid>f01ce634-e553-4e18-873c-49106b496736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>7642aad7-1b4e-4068-880e-2c07d69e8bfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'items[2].layout[1].data.value' and @placeholder = 'เช่น 08:30 น.' and @type = 'text']</value>
      <webElementGuid>def65b13-4136-4f83-ad5d-de27044cba37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
