<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__items3.layout1.data.value</name>
   <tag></tag>
   <elementGuidId>81521ae2-1e45-4f12-9198-32faf702169b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='items[3].layout[1].data.value']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;items[3].layout[1].data.value&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>800dd191-897e-495d-95a3-3171126d1858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>items[3].layout[1].data.value</value>
      <webElementGuid>cdb8b321-4c5b-4bdf-a40d-c8586c150556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-lg input-component</value>
      <webElementGuid>ba2dda44-78f1-47ba-9cea-d6bb82961c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>เช่น 18:30 น.</value>
      <webElementGuid>e548b6a7-9358-4dce-af7a-1fc1085f91e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2aef0173-c609-4313-85c8-d38b0383daa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic&quot;)/div[@class=&quot;set-padding-core-control row&quot;]/div[@class=&quot;padding-controller col-xl-4 col-md-4 col-sm-12 col-12&quot;]/div[@class=&quot;input-component-container&quot;]/input[@class=&quot;ant-input ant-input-lg input-component&quot;]</value>
      <webElementGuid>3cf3047f-a061-408c-b045-ebdc57830b7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='items[3].layout[1].data.value']</value>
      <webElementGuid>314acc4c-9be8-4551-94de-15e6dd8c81c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div[4]/div[4]/div/input</value>
      <webElementGuid>9137aa0d-70d6-4148-bcb4-cadc23ee7ee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[4]/div/input</value>
      <webElementGuid>bd2f61fc-43b8-47de-9d6f-870e5746840a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'items[3].layout[1].data.value' and @placeholder = 'เช่น 18:30 น.' and @type = 'text']</value>
      <webElementGuid>5e43f4f5-066d-4b89-9334-ae82e576e969</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
