<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ant-input-number-input_1_2</name>
   <tag></tag>
   <elementGuidId>141f57c3-174a-4431-92ed-71e3b9a05d65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='5000']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ant-input-number.ant-input-number-lg.ant-input-number-in-form-item.input-component.text-right.false.ant-input-number-focused > div.ant-input-number-input-wrap > input.ant-input-number-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d4c246f5-2d15-4b11-82d8-3d9f78333208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b82cf13c-b61c-4ec4-b8ec-d51d73d98c0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>spinbutton</value>
      <webElementGuid>125b7dcc-900d-4f78-8395-d5618344378d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuenow</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>caf00d37-a71d-45ee-90d4-6c0f5a06d936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>86fc62c4-8ad2-4a39-bb13-1261066c96c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input-number-input</value>
      <webElementGuid>bafb097e-3b94-4158-8916-1d8deea37f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5000</value>
      <webElementGuid>aa839706-960e-470b-8f04-4720216a99b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-control&quot;)/div[@class=&quot;ant-table-container&quot;]/div[@class=&quot;ant-table-body&quot;]/table[1]/tbody[@class=&quot;ant-table-tbody&quot;]/tr[@class=&quot;ant-table-row ant-table-row-level-0 editable-row&quot;]/td[@class=&quot;ant-table-cell&quot;]/div[1]/div[@class=&quot;ant-row ant-form-item&quot;]/div[@class=&quot;ant-col ant-form-item-control&quot;]/div[@class=&quot;ant-form-item-control-input&quot;]/div[@class=&quot;ant-form-item-control-input-content&quot;]/div[@class=&quot;ant-input-number-group-wrapper input-component text-right false&quot;]/div[@class=&quot;ant-input-number-wrapper ant-input-number-group&quot;]/div[@class=&quot;ant-input-number ant-input-number-lg ant-input-number-in-form-item input-component text-right false ant-input-number-focused&quot;]/div[@class=&quot;ant-input-number-input-wrap&quot;]/input[@class=&quot;ant-input-number-input&quot;]</value>
      <webElementGuid>674bf73e-dcca-49cf-8016-1085717ab9e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='5000']</value>
      <webElementGuid>210882a6-b567-46cf-8dae-10ac28e3f9f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='table-control']/div/div[2]/table/tbody/tr[2]/td[4]/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>14419c1f-35b7-43bc-a742-7c43bf071095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>f4122fdd-532c-4aa6-b598-180ed3e9ac95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
