<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_</name>
   <tag></tag>
   <elementGuidId>2ca13f84-a992-4fbf-937f-fd062dc876e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.text-header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>972554e5-9561-4a4d-93cd-768d3a1da170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-header</value>
      <webElementGuid>b8a2cc35-79c2-4add-b511-47535546f3ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ยืนยันตนเรียบร้อย</value>
      <webElementGuid>43192f33-708d-40fd-a11d-785cb0507354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;error-page-container without-nav&quot;]/div[@class=&quot;forget-password-container&quot;]/div[@class=&quot;text-container&quot;]/p[@class=&quot;text-header&quot;]</value>
      <webElementGuid>83c53ecf-c54f-424d-8b09-e094b8836002</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/p</value>
      <webElementGuid>86dcba00-d30c-4d1d-94cf-5bca378e9ddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ย้อนกลับไปหน้าเข้าสู่ระบบ'])[1]/preceding::p[1]</value>
      <webElementGuid>16c56606-3916-4485-b53d-cc1a5be189de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ยืนยันตนเรียบร้อย']/parent::*</value>
      <webElementGuid>2db4d73a-e6cf-4a96-972c-05ecb42eaca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>294b4f7a-8a35-4632-b954-4ede6038fc5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'ยืนยันตนเรียบร้อย' or . = 'ยืนยันตนเรียบร้อย')]</value>
      <webElementGuid>fac1438d-e51c-46df-a6d7-fb432910ca87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/form/div/div[2]/div/p</value>
      <webElementGuid>19c9bfa8-e157-45e6-ac3e-5ba1c34cfbc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password?'])[1]/preceding::p[1]</value>
      <webElementGuid>7a0cace0-330c-44e9-a77f-75adebff5951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/preceding::p[1]</value>
      <webElementGuid>ddbd6c90-6eaa-4e60-a31d-4ef074bbec1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='กรุณากรอกรหัสผ่าน']/parent::*</value>
      <webElementGuid>2ef77fc1-4b8b-4dc3-a561-078e43cc1e16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p</value>
      <webElementGuid>e352d473-6edb-4f84-8ce8-a16d06f56b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'กรุณากรอกรหัสผ่าน' or . = 'กรุณากรอกรหัสผ่าน')]</value>
      <webElementGuid>723b2e27-1b80-4657-8a9b-046ffd05060c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
