<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_AC01  - Petty Cash Voucher</name>
   <tag></tag>
   <elementGuidId>bdb00e67-1b6b-469d-9663-d982b35e2455</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-sm-6.col-12 > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div/div[4]/div/div[2]/div/div/div/p</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'AC01: แบบฟอร์มเบิกเงินสดย่อย - Petty Cash Voucher' or . = 'AC01: แบบฟอร์มเบิกเงินสดย่อย - Petty Cash Voucher')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>d81d023c-731a-4185-bd96-9ac73549161e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-form-type</value>
      <webElementGuid>4b783255-7026-485e-b870-2bd6962d238b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AC01: แบบฟอร์มเบิกเงินสดย่อย - Petty Cash Voucher</value>
      <webElementGuid>fbe8fccf-7d37-4252-8aa4-ac46d72169d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;request-main-container fade-enter-done&quot;]/div[@class=&quot;request-container&quot;]/div[@class=&quot;inner-content&quot;]/div[@class=&quot;worklist-items-container&quot;]/div[@class=&quot;request-container-item&quot;]/div[1]/div[@class=&quot;set-layout-in-row-respone row&quot;]/div[@class=&quot;col-sm-6 col-12&quot;]/p[1]</value>
      <webElementGuid>b29f5ab5-ff96-4cec-9275-2725d56621f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[4]/div/div[2]/div/div/div/p</value>
      <webElementGuid>e84bef7b-1cde-4384-a42b-ca19a0a9a6a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[3]/following::p[1]</value>
      <webElementGuid>b9906344-63ae-4a48-87dc-a710fce5a349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='History'])[2]/following::p[1]</value>
      <webElementGuid>55ec8013-d3c5-42f1-af45-903ff4dec8d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Draft'])[1]/preceding::p[1]</value>
      <webElementGuid>2765d41a-8e6e-433f-b98c-29e287b8234c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company'])[1]/preceding::p[5]</value>
      <webElementGuid>db0a6717-5353-4216-ab61-9168828ae3a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AC01: แบบฟอร์มเบิกเงินสดย่อย - Petty Cash Voucher']/parent::*</value>
      <webElementGuid>06b919b1-e76b-4926-869c-be8a941eec7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/p</value>
      <webElementGuid>3c8a1f1c-bb6b-48b8-bd61-f8bf5de4c5f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'AC01: แบบฟอร์มเบิกเงินสดย่อย - Petty Cash Voucher' or . = 'AC01: แบบฟอร์มเบิกเงินสดย่อย - Petty Cash Voucher')]</value>
      <webElementGuid>0dff01ea-2ff1-4c04-a9a9-5b1a2ca82c6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div/div[2]/div/div[2]/div[2]/div/div/div[3]/p</value>
      <webElementGuid>4c8ca8e4-b9bc-4b7a-8a57-24a6a9c4a920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='แบบฟอร์มเบิกเงินสดย่อย / Petty Cash Voucher'])[1]/following::p[2]</value>
      <webElementGuid>83f98292-2aeb-46b8-a4f3-1b92f3e64f14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AC01-2023-000017'])[1]/following::p[4]</value>
      <webElementGuid>fefa1fff-fda7-4437-99f1-fc9510ec35fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Draft'])[2]/preceding::p[11]</value>
      <webElementGuid>89c5cf91-c671-451c-918a-c44210172471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[3]/p</value>
      <webElementGuid>88d045f9-40ab-45c9-b739-04fb76e473c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
