<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Waiting for</name>
   <tag></tag>
   <elementGuidId>110e8a2a-cb38-4ffc-be7e-0c01445b8571</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.waiting-for-container > p.text-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div[2]/p</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//p[@class = 'text-name' and @id = 'TestAccurateWaitfor']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>42e79910-ef9e-49c1-827a-956cf942e7d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-name</value>
      <webElementGuid>f519b552-0f02-443f-a032-2fd1d7e5df8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TestAccurateWaitfor</value>
      <webElementGuid>b96fd190-a740-4921-b1ca-bf2518b4e10e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div[2]/p</value>
      <webElementGuid>d9ad2ed1-77db-4b3c-b7d3-b98876d182a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wait for Approve'])[1]/following::p[3]</value>
      <webElementGuid>25eb051e-a42e-4f4c-a17f-3e7b867ecde0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bee Naphat Test'])[1]/following::p[5]</value>
      <webElementGuid>a90762b4-13c9-4149-a8d4-f6765aecb8e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approve'])[1]/preceding::p[2]</value>
      <webElementGuid>f1cec246-b456-4a5c-a15f-e992a1ffa2ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wait for Approve'])[2]/preceding::p[8]</value>
      <webElementGuid>d7a741f7-0c4e-4c9c-a8b1-e695c298be31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Waiting for']/parent::*</value>
      <webElementGuid>2d77ba28-eac4-4fb0-8623-cfe23be1fc86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div/div[2]/p</value>
      <webElementGuid>322df875-cf85-4d98-b777-257bea20dd9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Waiting for' or . = 'Waiting for')]</value>
      <webElementGuid>22942d10-3204-45a4-8a61-1737d8778036</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
