<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_EMP001</name>
   <tag></tag>
   <elementGuidId>deb0f5f3-4ef8-4a5a-9569-4a20a6fdb763</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pr_id_48_content']/div/div/table/tbody/tr/td/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.tooltip-data > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f85486de-2474-44e2-9054-3a04c55c6194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EMP001</value>
      <webElementGuid>e733bfa1-8c65-40c6-83ce-2b48e53a680a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_48_content&quot;)/div[@class=&quot;p-datatable p-component p-datatable-selectable p-datatable-responsive-scroll&quot;]/div[@class=&quot;p-datatable-wrapper&quot;]/table[@class=&quot;p-datatable-table&quot;]/tbody[@class=&quot;p-datatable-tbody&quot;]/tr[@class=&quot;p-selectable-row&quot;]/td[1]/div[@class=&quot;tooltip-data&quot;]/span[1]</value>
      <webElementGuid>14766982-5c69-498a-b4eb-e44dea34d066</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_48_content']/div/div/table/tbody/tr/td/div/span</value>
      <webElementGuid>2699f825-1b6c-4d0c-ac11-ea76d75d8d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No available options'])[1]/following::span[7]</value>
      <webElementGuid>b9295713-ccd4-495b-a0d6-b7a72ac66cd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#'])[1]/following::span[12]</value>
      <webElementGuid>d54ef816-e903-4615-9521-4144e4fc1b2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WOLF ADMIN'])[1]/preceding::span[1]</value>
      <webElementGuid>cd151b1f-fa19-4ac8-b27f-280d6d3eabb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chief Executive Officer (CEO)'])[1]/preceding::span[2]</value>
      <webElementGuid>d0ad1e65-17b8-4847-b23d-d8b9ab31519f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='EMP001']/parent::*</value>
      <webElementGuid>332877fd-94b7-4edc-8736-800eb94cca2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/span</value>
      <webElementGuid>02d97065-47b0-4d5f-9d2c-03ed8b34969f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'EMP001' or . = 'EMP001')]</value>
      <webElementGuid>16255131-ec01-4d7e-8c32-a05e5af5b81b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
