<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Submitted</name>
   <tag></tag>
   <elementGuidId>85c3cbf2-2153-46cc-a5ed-320cfcc632d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div/div[4]/div/div[2]/div/div/div/div/div/p/div/div/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button
[(text() = 'Submitted' or . = 'Submitted') and @id = 'draftButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.action-badge > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button
</value>
      <webElementGuid>e3f460bb-28d1-4c8c-95bd-1a064f9d6efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submitted</value>
      <webElementGuid>ea660a0a-f7e7-4146-b9fd-ff3a48de186b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;request-main-container fade-enter-done&quot;]/div[@class=&quot;request-container&quot;]/div[@class=&quot;inner-content&quot;]/div[@class=&quot;worklist-items-container&quot;]/div[@class=&quot;request-container-item&quot;]/div[1]/div[@class=&quot;Histwo overflow-auto&quot;]/div[@class=&quot;HistoryCard&quot;]/div[@class=&quot;HistoryDetail&quot;]/div[@class=&quot;content-left-side&quot;]/p[@class=&quot;content-text-name&quot;]/div[@class=&quot;content-right-side&quot;]/div[@class=&quot;action-badge&quot;]/span[1]</value>
      <webElementGuid>3d0c9a6a-2862-4a21-969a-8ca96eb03cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>draftButton</value>
      <webElementGuid>ff136cd4-1fff-41d5-967b-a28717ceb0a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[4]/div/div[2]/div/div/div/div/div/p/div/div/span</value>
      <webElementGuid>24e1e860-6a65-4058-bf99-2393c07604d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='History'])[2]/following::span[1]</value>
      <webElementGuid>259957a2-4385-4eb2-b3ff-38ab6ed8af6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attachment'])[2]/following::span[1]</value>
      <webElementGuid>5d42e9f4-d05c-49f8-b92e-105201c5732a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submitted']/parent::*</value>
      <webElementGuid>5e91e274-9e5c-4688-970d-1a3f084815f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/div/div/span</value>
      <webElementGuid>34c81006-d644-4f5b-b325-48d279c0a14d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Submitted' or . = 'Submitted')]</value>
      <webElementGuid>e3de9432-e147-4b7b-8ad7-79bac0731ac5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
