<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_1</name>
   <tag></tag>
   <elementGuidId>c2be38ff-789f-4990-a418-623048fa3856</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.ant-pagination.ant-table-pagination.ant-table-pagination-right</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='basic']/div[3]/div[2]/div/div/div/div/div/ul</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>c9cfc80e-31c9-44c1-905a-7fd8d4fe357b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-pagination ant-table-pagination ant-table-pagination-right</value>
      <webElementGuid>2c94d157-c2ed-4e41-a462-11000c03c2ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>unselectable</value>
      <webElementGuid>4c532327-f310-4971-a4e3-76a0fd14a729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>871d0bdc-e18d-463f-98c5-2dfc1629f1db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic&quot;)/div[@class=&quot;set-padding-core-control row&quot;]/div[2]/div[@class=&quot;set-layout-required&quot;]/div[@class=&quot;padding-controller col-xl-12 col-md-12 col-sm-12 col-12&quot;]/div[@class=&quot;ant-table-wrapper padding-controller control-table false&quot;]/div[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container&quot;]/ul[@class=&quot;ant-pagination ant-table-pagination ant-table-pagination-right&quot;]</value>
      <webElementGuid>112f3b31-98c4-41fb-a637-40bd2286c598</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div[3]/div[2]/div/div/div/div/div/ul</value>
      <webElementGuid>862c7665-ebac-42eb-a4ba-d60181e8b36d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload'])[2]/following::ul[1]</value>
      <webElementGuid>113d1d5c-851c-4547-b31c-8c9264221d94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload'])[1]/following::ul[1]</value>
      <webElementGuid>afbb5997-7aad-4147-80a9-382f3e1c548c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remark'])[1]/preceding::ul[1]</value>
      <webElementGuid>29173354-93d8-4675-9c33-4cd85f754dd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul</value>
      <webElementGuid>a80ac810-4a7d-4462-ae0b-2d36baa4ba66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[(text() = '1' or . = '1')]</value>
      <webElementGuid>6d80a649-6cd6-4a18-99a1-6ba5b31168d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
