<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_jpegtest.jpg</name>
   <tag></tag>
   <elementGuidId>92bd51b1-ed20-4a58-bc73-2252d7aa338a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.set-pointer-css-attachment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div/div[4]/div/div[2]/div/div[3]/div/div/div[2]/div[3]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>e3dda9ad-ce2a-4df1-9cbf-a34e8064b541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>set-pointer-css-attachment</value>
      <webElementGuid>e77d85bb-49be-4bda-a243-91599d4ee967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>jpegtest.jpg</value>
      <webElementGuid>75aa351e-db73-4a0f-98ab-437516a46691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;request-main-container fade-enter-done&quot;]/div[@class=&quot;request-container&quot;]/div[@class=&quot;inner-content&quot;]/div[@class=&quot;worklist-items-container&quot;]/div[@class=&quot;request-container-item&quot;]/div[1]/div[3]/div[1]/div[@class=&quot;attachForm&quot;]/div[@class=&quot;innerAtt&quot;]/div[@class=&quot;detail-FileAtt&quot;]/p[@class=&quot;set-pointer-css-attachment&quot;]</value>
      <webElementGuid>44152d57-81d4-405a-94c5-6dd0c6d793cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[4]/div/div[2]/div/div[3]/div/div/div[2]/div[3]/p</value>
      <webElementGuid>27026031-16ab-473c-9e85-d85497bba992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/following::p[3]</value>
      <webElementGuid>c61e655f-985f-4099-bdee-ddca5c3a3403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Merge'])[1]/following::p[3]</value>
      <webElementGuid>cdafde03-a3e2-4c8d-896f-cbaf36bd9027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='jpegtest.jpg']/parent::*</value>
      <webElementGuid>0ba19da8-f819-4e0a-be98-74ea5cde8faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/p</value>
      <webElementGuid>d7febc7c-5a8f-4c95-87ce-762fb4d7531d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'jpegtest.jpg' or . = 'jpegtest.jpg')]</value>
      <webElementGuid>24e83188-437b-4371-861f-12e5b92eac18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
