<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_TEST_UPLOAD_ATTACHMENT.docx</name>
   <tag></tag>
   <elementGuidId>35276846-bd99-4952-8284-611bdafaa8f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div/div[4]/div/div[2]/div/div[3]/div/div/div[5]/div[3]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>8b3951b5-18b7-48ac-a697-8577f3d384e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>set-pointer-css-attachment</value>
      <webElementGuid>982d4226-2f21-44b6-8a49-2626938f4d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TEST_UPLOAD_ATTACHMENT.docx</value>
      <webElementGuid>e9c78ae8-1787-47f6-8862-750a2d83dd85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;request-main-container fade-enter-done&quot;]/div[@class=&quot;request-container&quot;]/div[@class=&quot;inner-content&quot;]/div[@class=&quot;worklist-items-container&quot;]/div[@class=&quot;request-container-item&quot;]/div[1]/div[3]/div[1]/div[@class=&quot;attachForm&quot;]/div[@class=&quot;innerAtt&quot;]/div[@class=&quot;detail-FileAtt&quot;]/p[@class=&quot;set-pointer-css-attachment&quot;]</value>
      <webElementGuid>86089f94-5c57-4ac3-a6cf-4448ae1f8c7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[4]/div/div[2]/div/div[3]/div/div/div[5]/div[3]/p</value>
      <webElementGuid>cc223d08-cdb8-4529-ba00-ee8586d24458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/following::p[15]</value>
      <webElementGuid>7fc54aef-1c54-4027-9aa4-90433f1668f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Merge'])[1]/following::p[15]</value>
      <webElementGuid>4f0323dd-ede7-4fee-a937-e25db6b9907a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TEST_UPLOAD_ATTACHMENT.docx']/parent::*</value>
      <webElementGuid>a6df7a5c-ce25-4332-83da-35a563ed3cec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/p</value>
      <webElementGuid>d10e837f-2a32-4132-b752-aa0023a8a00e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'TEST_UPLOAD_ATTACHMENT.docx' or . = 'TEST_UPLOAD_ATTACHMENT.docx')]</value>
      <webElementGuid>02f027cb-789a-48f3-9234-e4d54aa02727</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
