<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_TESTFile.xlsx</name>
   <tag></tag>
   <elementGuidId>d3c9a641-fb11-4eee-8e30-31e124f79e43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div/div[4]/div/div[2]/div/div[3]/div/div/div[7]/div[3]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>3977d6fe-4186-495d-802e-fc55f14ccc90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>set-pointer-css-attachment</value>
      <webElementGuid>c99d2fb6-b895-4e69-9438-26c66b6e12e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TESTFile.xlsx</value>
      <webElementGuid>1758046d-cf4f-4751-8aea-eaf5b39179c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;request-main-container fade-enter-done&quot;]/div[@class=&quot;request-container&quot;]/div[@class=&quot;inner-content&quot;]/div[@class=&quot;worklist-items-container&quot;]/div[@class=&quot;request-container-item&quot;]/div[1]/div[3]/div[1]/div[@class=&quot;attachForm&quot;]/div[@class=&quot;innerAtt&quot;]/div[@class=&quot;detail-FileAtt&quot;]/p[@class=&quot;set-pointer-css-attachment&quot;]</value>
      <webElementGuid>0b5461b0-7cc5-4fc3-9e99-32bb9ea9a85b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[4]/div/div[2]/div/div[3]/div/div/div[7]/div[3]/p</value>
      <webElementGuid>e871b840-73d7-493a-bf99-eab4ae050bac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/following::p[23]</value>
      <webElementGuid>e107b66f-bfad-48d4-af1e-200d99e487a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Merge'])[1]/following::p[23]</value>
      <webElementGuid>7697a29d-4d2a-42ba-8be3-2e0ba7507594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TESTFile.xlsx']/parent::*</value>
      <webElementGuid>81328823-59da-433d-ba05-41d77072fc5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[3]/p</value>
      <webElementGuid>4e2cb4cc-a873-4005-b1ae-f98aecf132ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'TESTFile.xlsx' or . = 'TESTFile.xlsx')]</value>
      <webElementGuid>e590c6a3-b990-407f-a294-67f2a9298eab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
