<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Test_Data.pptx</name>
   <tag></tag>
   <elementGuidId>c2836d2b-caa9-4fa3-b1c4-96175fc19d17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div/div[4]/div/div[2]/div/div[3]/div/div/div[4]/div[3]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>d32bcdec-e2c5-4f5f-ace7-ddd991d04ad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>set-pointer-css-attachment</value>
      <webElementGuid>cf8c6b1b-7c18-4820-a4d8-400fe21ec967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test_Data.pptx</value>
      <webElementGuid>bf806bef-265e-450a-aef0-69f8e638f9cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;request-main-container fade-enter-done&quot;]/div[@class=&quot;request-container&quot;]/div[@class=&quot;inner-content&quot;]/div[@class=&quot;worklist-items-container&quot;]/div[@class=&quot;request-container-item&quot;]/div[1]/div[3]/div[1]/div[@class=&quot;attachForm&quot;]/div[@class=&quot;innerAtt&quot;]/div[@class=&quot;detail-FileAtt&quot;]/p[@class=&quot;set-pointer-css-attachment&quot;]</value>
      <webElementGuid>042e77e8-1803-4dfe-8495-19451ec58c54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[4]/div/div[2]/div/div[3]/div/div/div[4]/div[3]/p</value>
      <webElementGuid>86489973-b5fd-4812-8b43-40fafda18ba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/following::p[11]</value>
      <webElementGuid>5fca628b-c927-4215-b6d3-3d2af702420d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Merge'])[1]/following::p[11]</value>
      <webElementGuid>796b3b16-180c-49ca-87c2-a6c0c2d5670c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Test_Data.pptx']/parent::*</value>
      <webElementGuid>6bd786c6-43c5-49b1-be8d-26db9441d080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/p</value>
      <webElementGuid>af012ef1-be8e-485f-8e6f-697040206a1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Test_Data.pptx' or . = 'Test_Data.pptx')]</value>
      <webElementGuid>9b41627a-7e74-48e8-83af-105984987000</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
