<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_-confirm-</name>
   <tag></tag>
   <elementGuidId>f64deab0-2203-41a3-8a9b-71a146275bac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.rps_5475 > div > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ReadingPaneContainerId']/div/div/div/div[2]/div/div/div/div/div/div/div/div[3]/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>77e76c43-b4b1-452a-a554-03501f63d442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://qar2.wolfapprove.com/Verify?PK=e3be0218-1083-4235-95da-c7f46a0abd2a</value>
      <webElementGuid>f4a409a6-6825-4481-b850-c83c5644751e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>a3e97686-23ac-4139-825f-e2cf99c10bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener noreferrer</value>
      <webElementGuid>cdbc1f49-80d8-4647-b202-64f99e4bc0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-auth</name>
      <type>Main</type>
      <value>NotApplicable</value>
      <webElementGuid>055ff902-93f1-4144-8307-258bbf866742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-safelink</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9924f31c-893e-48ec-9828-4414baafec1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-linkindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f5fa544e-7b69-45d1-a1c6-be781febafaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-confirm-</value>
      <webElementGuid>eec11d00-595d-4226-affb-dd8d03e0b9be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReadingPaneContainerId&quot;)/div[1]/div[@class=&quot;g_zET&quot;]/div[@class=&quot;MtujV&quot;]/div[@class=&quot;L72vd&quot;]/div[@class=&quot;Q8TCC yyYQP customScrollBar&quot;]/div[1]/div[@class=&quot;aVla3&quot;]/div[1]/div[1]/div[@class=&quot;wide-content-host&quot;]/div[@class=&quot;SlLx9 isFirstCard byzS1&quot;]/div[@class=&quot;XbIp4 jmmB7 GNqVo yxtKT allowTextSelection&quot;]/div[1]/div[@class=&quot;rps_5475&quot;]/div[1]/a[1]</value>
      <webElementGuid>bb8d5dee-346e-43a8-babc-3d44d08096a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ReadingPaneContainerId']/div/div/div/div[2]/div/div/div/div/div/div/div/div[3]/div/div/div/a</value>
      <webElementGuid>2c14a829-b184-41cc-b9a8-6b5196784826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'-confirm-')]</value>
      <webElementGuid>b5f8fb3f-24d1-43d5-a25f-39cedf1ecab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wed 1/18/2023 5:18 PM'])[1]/following::a[1]</value>
      <webElementGuid>3dca18b0-5f98-4ad5-a0fb-195f1937b7c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='workflow mail'])[14]/following::a[1]</value>
      <webElementGuid>0718b5f7-e080-45e4-88f4-d7432868abd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reply'])[2]/preceding::a[1]</value>
      <webElementGuid>23470b6d-f2db-441f-befe-700121f00e89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reply all'])[2]/preceding::a[1]</value>
      <webElementGuid>b759c13b-5876-40ab-8346-8b9feb7efa85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='-confirm-']/parent::*</value>
      <webElementGuid>518746aa-e940-45ba-87c5-e3696d91de11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://qar2.wolfapprove.com/Verify?PK=e3be0218-1083-4235-95da-c7f46a0abd2a')]</value>
      <webElementGuid>2f1374ac-4059-4f0d-a16e-72dcf99f2e05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/a</value>
      <webElementGuid>260d54ba-4cee-4c5d-8c8e-477e1f7a938d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://qar2.wolfapprove.com/Verify?PK=e3be0218-1083-4235-95da-c7f46a0abd2a' and (text() = '-confirm-' or . = '-confirm-')]</value>
      <webElementGuid>63dbfc1c-62bc-4955-b2d2-332b1c9e7480</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
