<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_workflow mailWOLF Approve Confirm to ch_4994af</name>
   <tag></tag>
   <elementGuidId>d085a985-5d8c-4d3e-af25-5d88cec89a8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.XG5Jd.JtO0E</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AQAAARaO2ogBAAADql7v4AAAAAA=']/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bcec29f0-fad7-4cf8-827d-723b4235b126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>XG5Jd JtO0E</value>
      <webElementGuid>79d7cf42-9397-4f2d-a309-dad3e85eceae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>workflow mail[WOLF Approve] Confirm to change password5:18 PMDear user Please confirm to change password for access WOLF Approve -confirm- [THIS IS AN AUTOMATED MESSAGE - PLEASE DO NOT REPLY DIRECTLY TO THIS EMAIL] To : wolf01@qar2.com CC :</value>
      <webElementGuid>aa600525-6d62-48f0-975a-7d6eee735844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AQAAARaO2ogBAAADql7v4AAAAAA=&quot;)/div[1]/div[@class=&quot;zKDWD YbB6r IKvQi IjQyD JCRRb cSOXK G1NES&quot;]/div[@class=&quot;XG5Jd JtO0E&quot;]</value>
      <webElementGuid>d37568f8-6a68-4fac-935e-ee54f00e3cee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AQAAARaO2ogBAAADql7v4AAAAAA=']/div/div/div</value>
      <webElementGuid>2a6db7fc-607b-4e7a-b757-c734dd857258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>60e7aa44-904f-49b1-98f7-f2a57f2fb803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'workflow mail[WOLF Approve] Confirm to change password5:18 PMDear user Please confirm to change password for access WOLF Approve -confirm- [THIS IS AN AUTOMATED MESSAGE - PLEASE DO NOT REPLY DIRECTLY TO THIS EMAIL] To : wolf01@qar2.com CC :' or . = 'workflow mail[WOLF Approve] Confirm to change password5:18 PMDear user Please confirm to change password for access WOLF Approve -confirm- [THIS IS AN AUTOMATED MESSAGE - PLEASE DO NOT REPLY DIRECTLY TO THIS EMAIL] To : wolf01@qar2.com CC :')]</value>
      <webElementGuid>0f872c79-467c-4088-805e-fd0198e26d63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
