<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Surname_items1.layout1.data.value</name>
   <tag></tag>
   <elementGuidId>c5e07c4b-0736-4425-ad94-464754b4882a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;items[1].layout[1].data.value&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='items[1].layout[1].data.value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3225ad30-c19c-4a51-8695-dfc0b38f9fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>items[1].layout[1].data.value</value>
      <webElementGuid>dfb68fb8-2718-4887-8d6b-0f4c2da622d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-disabled ant-input-lg input-component</value>
      <webElementGuid>7343cd6b-43c9-4d39-b8ec-331422f84d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a4f5f926-13bc-4575-bc6d-6a2baafb3ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Test</value>
      <webElementGuid>85c8cccd-10c4-4f71-8bbc-3fd4925de8c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic&quot;)/div[@class=&quot;set-padding-core-control row&quot;]/div[@class=&quot;padding-controller col-xl-4 col-md-4 col-sm-12 col-12&quot;]/div[@class=&quot;input-component-container&quot;]/input[@class=&quot;ant-input ant-input-disabled ant-input-lg input-component&quot;]</value>
      <webElementGuid>431f881d-c665-484e-8788-a70347b11a3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='items[1].layout[1].data.value']</value>
      <webElementGuid>522173c8-1640-454c-8ab6-4cbfd6049606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div[2]/div[4]/div/input</value>
      <webElementGuid>b27a7f53-e6c9-45f1-9918-5f251b97f7d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>5b51abb6-e80a-4a9a-8521-c9ac5e8f05bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'items[1].layout[1].data.value' and @type = 'text']</value>
      <webElementGuid>0a00fab3-991b-4e57-8839-e1f9983c6844</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
