<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Copy</name>
   <tag></tag>
   <elementGuidId>fc21d8d2-b14d-4dcd-93f0-75cadff473d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div/div[2]/div[2]/div[2]/button[2]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.memo-button.copy > p</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button
[(text() = ' Copy' or . = ' Copy') and @class = 'memo-button copy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button
</value>
      <webElementGuid>2492220e-9e22-4ef5-9af5-20fa614201f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Copy</value>
      <webElementGuid>0935cb55-d6a8-4edf-b215-8322a7793a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;request-main-container fade-enter-done&quot;]/div[@class=&quot;request-container&quot;]/div[@class=&quot;header-request set-z-index&quot;]/div[@class=&quot;confirm-container&quot;]/div[@class=&quot;memo-button-container&quot;]/button[@class=&quot;memo-button copy&quot;]/p[1]</value>
      <webElementGuid>b46e2fef-da42-4ef0-9079-7e9459a75194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>memo-button copy</value>
      <webElementGuid>88459277-9ef5-4d41-8f50-3f27c2b18970</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[2]/div[2]/div[2]/button[2]/p</value>
      <webElementGuid>2b081c0a-4028-4262-ba32-e146e470e22e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Requestor'])[1]/preceding::p[2]</value>
      <webElementGuid>04028b8f-8ce2-4c4e-b1c3-2ab75212ada0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/preceding::p[2]</value>
      <webElementGuid>72ed4cbd-8fb5-4284-8229-8e2c291aeda8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Copy']/parent::*</value>
      <webElementGuid>8ef4c1c4-ea6d-406c-88df-beb997e649d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]/p</value>
      <webElementGuid>56a386ee-01a7-464a-90fc-927a5c740e2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = ' Copy' or . = ' Copy')]</value>
      <webElementGuid>ccb18680-fba3-4bef-9bc9-8f7733daf063</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
