<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_TESTFile.xlsx</name>
   <tag></tag>
   <elementGuidId>2667f4c4-7206-46a3-9a7f-2c2fa8b83c87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div/div[4]/div/div[2]/div/div[3]/div/div/div[2]/div[3]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.set-pointer-css-attachment</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'TESTFile.xlsx' or . = 'TESTFile.xlsx') and @file = 'D:\TestData\TESTFile.xlsx']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>48ad2d97-ede0-4809-bba3-64fa62048733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>set-pointer-css-attachment</value>
      <webElementGuid>81b6b57d-b565-4e50-a27e-c9b98cd49d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TESTFile.xlsx</value>
      <webElementGuid>34c733a1-867a-48ef-b25c-1aa230798b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;request-main-container fade-enter-done&quot;]/div[@class=&quot;request-container&quot;]/div[@class=&quot;inner-content&quot;]/div[@class=&quot;worklist-items-container&quot;]/div[@class=&quot;request-container-item&quot;]/div[1]/div[3]/div[1]/div[@class=&quot;attachForm&quot;]/div[@class=&quot;innerAtt&quot;]/div[@class=&quot;detail-FileAtt&quot;]/p[@class=&quot;set-pointer-css-attachment&quot;]</value>
      <webElementGuid>5e12827c-c943-4c9a-afd1-f5cd3ecb628f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>file</name>
      <type>Main</type>
      <value>D:\TestData\TESTFile.xlsx</value>
      <webElementGuid>d02cad70-7e95-43d7-8f8f-2a66b4ea3942</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[4]/div/div[2]/div/div[3]/div/div/div[2]/div[3]/p</value>
      <webElementGuid>0d8a1ab8-45a9-4ae1-8a12-1ddcd8cdf327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/following::p[3]</value>
      <webElementGuid>7c61f018-b583-4d2c-91ed-b9a833c1aa48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Merge'])[1]/following::p[3]</value>
      <webElementGuid>799bcb35-a491-419a-abba-972734ba2976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TESTFile.xlsx']/parent::*</value>
      <webElementGuid>3b6d278c-651c-4f23-be44-230e5b2fc8bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/p</value>
      <webElementGuid>85a16d8b-040c-44c3-95fc-a6fa8d5710e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'TESTFile.xlsx' or . = 'TESTFile.xlsx')]</value>
      <webElementGuid>302bde42-74b0-4b0d-bd9b-b82efefaa538</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
