<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_TFCR_01-2023-000001</name>
   <tag></tag>
   <elementGuidId>a83c8acf-f55e-476d-86f9-6391d013bc6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div/div/div[2]/div/div/div[2]/div/div[3]/div/div/p</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@class = 'text-form-running' and (text() = 'TFCR_01-2023-000001' or . = 'TFCR_01-2023-000001') and @href = '/Request?MemoID=593']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.text-form-running</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ed386655-dba9-4dd9-993a-c6b4b0aa9f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-form-running</value>
      <webElementGuid>1932b444-3c51-4fd6-813c-7409cd753e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TFCR_01-2023-000001</value>
      <webElementGuid>3630b503-e750-43f4-ae23-0764dc3e7c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Request?MemoID=593</value>
      <webElementGuid>5d52159f-d5b5-43e8-a369-6ff5b679105f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div/div[2]/div/div/div[2]/div/div[3]/div/div/p</value>
      <webElementGuid>f143ab48-f498-46b1-9b5b-d3b3161d5462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Draft'])[1]/following::p[5]</value>
      <webElementGuid>486b6416-f947-47ad-bfaf-dd87d6d5029e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='testing change requester UAT'])[1]/following::p[7]</value>
      <webElementGuid>0344ea97-d8d7-4923-a83a-d6f2872554d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Draft'])[2]/preceding::p[6]</value>
      <webElementGuid>1886354c-b16e-4b77-9306-3cdbe86ba299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test'])[1]/preceding::p[12]</value>
      <webElementGuid>0388d30d-b820-43ab-a507-c732fafd8835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/div/p</value>
      <webElementGuid>1b4db408-5f82-477f-b2b5-541047396f27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'TFCR_01-2023-000001' or . = 'TFCR_01-2023-000001')]</value>
      <webElementGuid>59dc2de3-6b15-42ef-9208-159d882b0ffd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
