<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__inputTextComponents-width_1</name>
   <tag></tag>
   <elementGuidId>f699e245-42f4-490c-b6ed-fa05b9f3aefd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div/div[4]/div/div[2]/div/div[3]/div[5]/div[2]/div/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;root&quot;)/div[@class=&quot;request-main-container fade-enter-done&quot;]/div[@class=&quot;request-container&quot;]/div[@class=&quot;inner-content&quot;]/div[@class=&quot;worklist-items-container&quot;]/div[@class=&quot;request-container-item&quot;]/div[1]/div[@class=&quot;Information-panding-card&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl-10 col-sm-12 col-12&quot;]/div[1]/span[@class=&quot;inputTextComponents-width&quot;][count(. | //*[(text() = '**ห้ามกด approve หรือใดๆทั้งสิ้น ** Katalon Automate Test CopyForm ' or . = '**ห้ามกด approve หรือใดๆทั้งสิ้น ** Katalon Automate Test CopyForm ')]) = count(//*[(text() = '**ห้ามกด approve หรือใดๆทั้งสิ้น ** Katalon Automate Test CopyForm ' or . = '**ห้ามกด approve หรือใดๆทั้งสิ้น ** Katalon Automate Test CopyForm ')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7d0f39fd-7b73-4848-9653-a67c6005c8d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputTextComponents-width </value>
      <webElementGuid>d1c36b8f-46b2-4b7e-a3d0-cb79f5c96b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;request-main-container fade-enter-done&quot;]/div[@class=&quot;request-container&quot;]/div[@class=&quot;inner-content&quot;]/div[@class=&quot;worklist-items-container&quot;]/div[@class=&quot;request-container-item&quot;]/div[1]/div[@class=&quot;Information-panding-card&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl-10 col-sm-12 col-12&quot;]/div[1]/span[@class=&quot;inputTextComponents-width&quot;]</value>
      <webElementGuid>45d9a851-18ae-4523-a9e0-f0a0c817c96c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>**ห้ามกด approve หรือใดๆทั้งสิ้น ** Katalon Automate Test CopyForm </value>
      <webElementGuid>9894d800-d220-4222-ac28-c487d5f45528</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[4]/div/div[2]/div/div[3]/div[5]/div[2]/div/span</value>
      <webElementGuid>4f10d2fb-b6b1-42af-964e-4cb01b2e27da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subject'])[1]/following::span[2]</value>
      <webElementGuid>d250034a-3250-4c17-aefc-b351f1081da9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DueDate'])[1]/preceding::span[1]</value>
      <webElementGuid>3f4dc04e-183e-42dc-90cf-feb5bf619483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Surname'])[1]/preceding::span[4]</value>
      <webElementGuid>ffbdd19c-2a2a-470d-9613-23109096d1df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/span</value>
      <webElementGuid>b6c3aece-bdcb-41e7-99ff-ddaca2a35038</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
