<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Requestor</name>
   <tag></tag>
   <elementGuidId>b1217fbb-a02e-410c-8d0d-015b4db06cd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div/div[3]/div/div/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@class = 'BTN' and @id = 'Requestor']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.BTN</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>56eefc04-f492-4219-9528-5278cc9866d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>BTN</value>
      <webElementGuid>486c3c58-bf82-4091-a41a-f5148e90d818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Requestor</value>
      <webElementGuid>52b4b3bb-87bd-486a-9bc6-b015130340d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[3]/div/div/button</value>
      <webElementGuid>3054eb8f-ac51-4710-af95-82979be0f729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/preceding::button[1]</value>
      <webElementGuid>e1f2c42f-7366-4d46-ab69-6b6a78225abd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div/div/button</value>
      <webElementGuid>d974a611-07f7-472a-b4b9-df5bc6937da5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Requestor' or . = 'Requestor')]</value>
      <webElementGuid>7e32b623-c029-4793-9ac0-987ef8db5427</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
