<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(id(, , fil, , ))_fil</name>
   <tag></tag>
   <elementGuidId>e17aec84-0e5f-4d03-8031-b06439fda93f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fil']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fil</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>37ba5f8b-1467-434f-9e7c-8f998ec7d85c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-custom</value>
      <webElementGuid>dbef7ddd-12aa-470c-b394-ea4cb00b0d0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>55007106-c494-42b8-8dcc-9c7d985463b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fil</value>
      <webElementGuid>ff008f97-05b5-4091-b6f4-4a3abf992df5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ค้นหา ประเภทแบบฟอร์ม / แบบฟอร์ม</value>
      <webElementGuid>9bdd4b38-0f0e-4458-a3ae-967725b28a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fil</value>
      <webElementGuid>811902dc-0edb-4c44-a378-ed14b0f6fcd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fil&quot;)</value>
      <webElementGuid>5fea5972-844f-4908-8ff5-8a531ea731ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fil']</value>
      <webElementGuid>9475dca0-fb5e-4d1b-a0c0-47fca554107f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>cf0c55fb-4758-4368-b899-11b57a36b0b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'fil' and @placeholder = 'ค้นหา ประเภทแบบฟอร์ม / แบบฟอร์ม' and @id = 'fil']</value>
      <webElementGuid>7e38e2a5-6dda-427d-93c9-394ee2616fe7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
