<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_History_ant-input</name>
   <tag></tag>
   <elementGuidId>f44d5856-9782-416a-91a3-d961daf653e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='EMP002']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.ant-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70618728-30f2-451b-884d-533b94ab6201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input</value>
      <webElementGuid>44bc52ff-cbff-4e1d-b134-2ba30992d317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>edc888db-145c-4de3-b1fa-c3bb147d738d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>EMP002</value>
      <webElementGuid>15aa903f-e711-4b65-94cc-3ca2bc8bb4c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;request-main-container fade-enter-done&quot;]/div[@class=&quot;request-container&quot;]/div[@class=&quot;inner-content&quot;]/div[@class=&quot;worklist-items-container&quot;]/div[@class=&quot;request-container-item&quot;]/div[1]/div[@class=&quot;setrow-form-requestor row&quot;]/div[@class=&quot;col-md-4 col-sm-12 col-12&quot;]/span[@class=&quot;ant-input-group-wrapper ant-input-search set-search-form-requestor&quot;]/span[@class=&quot;ant-input-wrapper ant-input-group&quot;]/input[@class=&quot;ant-input&quot;]</value>
      <webElementGuid>7abe8e2c-ed69-43e3-b12a-93336f6d3f61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='EMP002']</value>
      <webElementGuid>8351ecf3-8fa2-491b-8634-b3c803bd61c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[4]/div/div[2]/div/div[2]/div[2]/span/span/input</value>
      <webElementGuid>99c89ea9-9548-4e01-9c95-a64a52ca3f51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/input</value>
      <webElementGuid>eda79da3-f95a-4176-8132-c525ddf15af2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>722508bf-3fa8-472f-90c0-b0d7f67c6db7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
