<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Department_search-filter-input</name>
   <tag></tag>
   <elementGuidId>d4fab900-3f6e-4760-b84d-f23ea919032b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[9]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.desktop > div.content.filter-content > div.worklist-filter-container > div.all-filter-container > div.Sidebar > div.search-filter-container > div.search-filter-input-component > input.search-filter-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1e47e05-9171-44e8-892b-e87d65ea3ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d436e55e-7365-4081-9f52-57a3fec9fcbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-filter-input</value>
      <webElementGuid>86e1916f-f797-4174-acc5-65e489a2d43e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>85ea46be-0ca8-46f0-9645-e11d13b70bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;main-worklist&quot;]/div[@class=&quot;main-container&quot;]/div[@class=&quot;worklist-container&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;worklist-items-container&quot;]/div[@class=&quot;desktop&quot;]/div[@class=&quot;content filter-content&quot;]/div[@class=&quot;worklist-filter-container&quot;]/div[@class=&quot;all-filter-container&quot;]/div[@class=&quot;Sidebar&quot;]/div[@class=&quot;search-filter-container&quot;]/div[@class=&quot;search-filter-input-component&quot;]/input[@class=&quot;search-filter-input&quot;]</value>
      <webElementGuid>9eda835b-d7f2-4946-a97c-e9e02b3d46a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[9]</value>
      <webElementGuid>292b2120-68f9-4212-87cf-69cb8eaeab8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div/div[2]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>d1850975-6aaa-4fcc-b38f-22033da42453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>c81907eb-c7d7-4322-9f74-d95676ff614b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search']</value>
      <webElementGuid>06e97b11-856e-4ba9-b476-d6bc83bad57d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
