<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Employee</name>
   <tag></tag>
   <elementGuidId>2fa16d0f-b121-4057-b7bd-cf58d63d0f0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Employee > label.button-submenu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='Employee']/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>193c185b-6969-4c3c-b6ca-f5d82f43f697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-submenu</value>
      <webElementGuid>b2e06fd2-f76c-43e6-88dc-c2a0cf7b20d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Employee</value>
      <webElementGuid>9065291d-5b06-4994-9b75-441405d2de2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Employee&quot;)/label[@class=&quot;button-submenu&quot;]</value>
      <webElementGuid>6f683d49-b06f-4933-a12d-343967b947d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='Employee']/label</value>
      <webElementGuid>c0972480-bfa9-45ff-9c25-cc1d48afef81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form Template'])[1]/following::label[1]</value>
      <webElementGuid>34b0f0ed-4f81-46be-8de6-6c4e213d77ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'Employee', '&quot;', ')/label[@class=', '&quot;', 'button-submenu', '&quot;', ']')])[1]/following::label[2]</value>
      <webElementGuid>57e6bf6e-d1e9-40f2-abde-dd1df0ce8bdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Department'])[1]/preceding::label[1]</value>
      <webElementGuid>174b2a66-43b4-4283-b1cd-c31e51ce4043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Position'])[1]/preceding::label[2]</value>
      <webElementGuid>df28b523-dcca-48ef-a9a8-927729cd401c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Employee']/parent::*</value>
      <webElementGuid>c4fbd085-8c83-489d-b84f-4f1b9be12cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/label</value>
      <webElementGuid>1530818b-3500-47fe-879f-c72ec6628c62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Employee' or . = 'Employee')]</value>
      <webElementGuid>45bb79a4-502c-4541-bb65-6f6772351dc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
