<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Search by ADTitle_p-button-icon p-c pi_c91be8</name>
   <tag></tag>
   <elementGuidId>3f863aba-027e-4d1d-8b10-63f7151fcf0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.p-button-icon.p-c.pi.pi-ellipsis-v</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ddd']/button[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3e9765da-5994-49df-be5e-4bd05bcdc1ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button-icon p-c pi pi-ellipsis-v</value>
      <webElementGuid>1e98d443-9396-4ee8-8c32-7aec182e669a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;main-container&quot;]/div[@class=&quot;worklist-container&quot;]/div[@class=&quot;dynamictable-container&quot;]/div[@class=&quot;ant-row&quot;]/div[@class=&quot;ant-col&quot;]/div[@class=&quot;ant-table-wrapper setting-datatable&quot;]/div[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;ant-table ant-table-middle ant-table-ping-right ant-table-fixed-header ant-table-fixed-column ant-table-scroll-horizontal ant-table-has-fix-left&quot;]/div[@class=&quot;ant-table-container&quot;]/div[@class=&quot;ant-table-body&quot;]/table[1]/tbody[@class=&quot;ant-table-tbody&quot;]/tr[@class=&quot;ant-table-row ant-table-row-level-0&quot;]/td[@class=&quot;ant-table-cell ant-table-cell-fix-left ant-table-cell-fix-left-last ant-table-cell-row-hover&quot;]/div[1]/div[@id=&quot;ddd&quot;]/button[@class=&quot;p-button p-component p-splitbutton-menubutton p-button-icon-only&quot;]/span[@class=&quot;p-button-icon p-c pi pi-ellipsis-v&quot;]</value>
      <webElementGuid>46a05df5-da22-4bc2-9c1a-736dd39e0b20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ddd']/button[2]/span</value>
      <webElementGuid>e32c4739-2750-4b8f-95e7-4712b62cc0db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span</value>
      <webElementGuid>ac2689b8-00da-49ae-9269-ea3d19819f3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
