<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>f98e1a25-bb0f-496d-b0a8-6aff6cbf3a38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pr_id_8_content']/div/div/table/tbody/tr[4]/td[2]/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f7fde046-09f1-4137-a456-14941bd8935c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ขวัญใจ เจริญผลวัฒนา</value>
      <webElementGuid>41e2a451-bd82-4a4d-b236-dc265698caa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_8_content&quot;)/div[@class=&quot;p-datatable p-component p-datatable-selectable p-datatable-responsive-scroll&quot;]/div[@class=&quot;p-datatable-wrapper&quot;]/table[@class=&quot;p-datatable-table&quot;]/tbody[@class=&quot;p-datatable-tbody&quot;]/tr[@class=&quot;p-selectable-row p-row-odd&quot;]/td[2]/div[@class=&quot;tooltip-data&quot;]/span[1]</value>
      <webElementGuid>d0798dab-b7d8-45ce-a3d2-ff77bd170fd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_8_content']/div/div/table/tbody/tr[4]/td[2]/div/span</value>
      <webElementGuid>fd8cd08d-a227-4e54-a226-875179d57bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EMP003'])[1]/following::span[1]</value>
      <webElementGuid>74f8345a-b366-447b-88b5-384d2fb9e9f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='บัญชีและการเงิน (AC)'])[1]/following::span[2]</value>
      <webElementGuid>f6f687f2-7407-4d35-b231-688b5e821454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ผู้จัดการฝ่ายสารสนเทศ'])[1]/preceding::span[1]</value>
      <webElementGuid>8c8c19c5-728e-4e71-a413-657c4d89a2f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ปฏิบัติการ'])[2]/preceding::span[2]</value>
      <webElementGuid>da3ab6cf-aa0c-4453-991e-68a50c5649a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ขวัญใจ เจริญผลวัฒนา']/parent::*</value>
      <webElementGuid>38178529-2527-4557-800e-0654ed5366f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/div/span</value>
      <webElementGuid>dd921eca-1aa5-458c-a815-8cd62bc6e16a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'ขวัญใจ เจริญผลวัฒนา' or . = 'ขวัญใจ เจริญผลวัฒนา')]</value>
      <webElementGuid>0a305806-196c-40d1-8655-fe9cf0b22af2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
