<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Edit</name>
   <tag></tag>
   <elementGuidId>a863df8a-9e66-48dd-9513-87d402cd595e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.p-menuitem-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ddd_overlay']/ul/li/a/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dc066b60-4488-4409-b51d-2b6b315f9f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-menuitem-text</value>
      <webElementGuid>eb32f680-edca-4d42-8d89-dec3cee666c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>8eba38a2-0d71-46c0-99e8-9869f73ab001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ddd_overlay&quot;)/ul[@class=&quot;p-menu-list p-reset&quot;]/li[@class=&quot;p-menuitem&quot;]/a[@class=&quot;p-menuitem-link&quot;]/span[@class=&quot;p-menuitem-text&quot;]</value>
      <webElementGuid>42686c78-81ce-4dac-8c46-c4d570025a76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ddd_overlay']/ul/li/a/span[2]</value>
      <webElementGuid>b866c975-10b6-43b5-adb2-d65adc2582e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='วูล์ฟ'])[10]/following::span[4]</value>
      <webElementGuid>5178bbca-b972-42d2-8928-4f1c441bc33a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[11]/following::span[4]</value>
      <webElementGuid>946b22a1-e2b5-4c17-a357-b045c87fd1ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>b3dfb26c-abd0-41f5-a5f2-1f45d581abcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span[2]</value>
      <webElementGuid>c7e86141-045a-4b95-9136-095d854c80bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>3f50b925-bb16-4cc5-bb0c-5a0685da7ad7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
