<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Confirm</name>
   <tag></tag>
   <elementGuidId>96df4022-8a18-41f1-9968-5b23e72e9eb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.Confirm-Button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pr_id_12']/div[3]/div/div/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>14cdcb88-eb0c-4a8d-ab47-eea82467407d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Confirm-Button</value>
      <webElementGuid>907b2042-5c28-4cf8-a15a-d98974e1c70a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirm</value>
      <webElementGuid>63ec3aaa-9046-4e39-8ad8-77464c4a9b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_12&quot;)/div[@class=&quot;p-dialog-footer&quot;]/div[@class=&quot;Button-line memo-button-padding&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl-6 col-sm-6 col-6&quot;]/button[@class=&quot;Confirm-Button&quot;]</value>
      <webElementGuid>787b6422-80bb-40bf-a0d4-01d54ea3229c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_12']/div[3]/div/div/div[2]/button</value>
      <webElementGuid>7d2e018b-10a9-46fc-b9e0-3e3b715f7123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>4c8ea6e4-6325-4250-9c78-71d703287ab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ชื่อ-สกุล'])[1]/following::button[2]</value>
      <webElementGuid>176c1833-c4a9-4531-b08a-d9909a19362c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirm']/parent::*</value>
      <webElementGuid>7c85dd70-a94b-4547-ac9b-b90d3d974e05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/button</value>
      <webElementGuid>bba46c02-25e4-41f6-8f01-56ac1caaf5df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Confirm' or . = 'Confirm')]</value>
      <webElementGuid>67e7494e-d05b-4ce1-9905-664b412c139c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
