<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>clickRequesterOnleftSide</name>
   <tag></tag>
   <elementGuidId>2c6c9847-f505-4490-bdc6-ea70cabdae62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div/div[3]/div/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.BTN</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'ผู้ยื่นคำร้อง' or . = 'ผู้ยื่นคำร้อง') and @id = 'Requestor']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1fa2eb1a-72eb-412e-9f08-48d6517f91a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>BTN</value>
      <webElementGuid>6dd1b0ca-6cfc-4aee-8efa-15c3e93e66f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ผู้ยื่นคำร้อง</value>
      <webElementGuid>fa67761f-db02-4a05-8a9a-6144f222c161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;request-main-container fade-enter-done&quot;]/div[@class=&quot;request-container&quot;]/div[@class=&quot;show-tablet-navbar-request-min-1024&quot;]/div[@class=&quot;Sidebar RequestSideBarElement-display-none&quot;]/div[1]/button[@class=&quot;BTN&quot;]</value>
      <webElementGuid>21197290-b01b-4990-b46d-8294fe4b6269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Requestor</value>
      <webElementGuid>d2ee9b44-2fb8-4b55-8bd6-6206be9dc696</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[3]/div/div/button</value>
      <webElementGuid>111ee55a-5220-4a8f-bace-509694d22dc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='รายละเอียด'])[1]/preceding::button[1]</value>
      <webElementGuid>fa37d670-3d40-44be-9230-f50757e68642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div/div/button</value>
      <webElementGuid>b4daea6a-27d6-41d1-8fa6-55105fe1dfcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'ผู้ยื่นคำร้อง' or . = 'ผู้ยื่นคำร้อง')]</value>
      <webElementGuid>080eba3b-94fd-4c64-b419-88cd1ed840d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
