<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__search-filter-input</name>
   <tag></tag>
   <elementGuidId>bbb98148-0f40-4aa3-bb9c-a7f47dfa7e62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.desktop > div.content.filter-content > div.worklist-filter-container > div.all-filter-container > div.Sidebar > div.search-filter-container > div.search-filter-input-component > input.search-filter-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>65a0e8ac-b913-4d51-b1f3-0c8343fb9a20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f15acf4b-4a80-43a7-854b-fff0119ca1a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-filter-input</value>
      <webElementGuid>6016a0a7-e7c9-424b-8088-145a6803b456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ค้นหา</value>
      <webElementGuid>254f8956-2ffd-442e-9ef1-7e4a7558329c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;main-worklist&quot;]/div[@class=&quot;main-container&quot;]/div[@class=&quot;worklist-container&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;worklist-items-container&quot;]/div[@class=&quot;desktop&quot;]/div[@class=&quot;content filter-content&quot;]/div[@class=&quot;worklist-filter-container&quot;]/div[@class=&quot;all-filter-container&quot;]/div[@class=&quot;Sidebar&quot;]/div[@class=&quot;search-filter-container&quot;]/div[@class=&quot;search-filter-input-component&quot;]/input[@class=&quot;search-filter-input&quot;]</value>
      <webElementGuid>4fddc770-ca28-421e-a796-e44ba18ffd57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[9]</value>
      <webElementGuid>515ac2c1-b2fe-4538-bfb8-d0ba14412983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div/div[2]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>9dd08092-bc23-45b6-824b-96904cd0ffa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>1b9a6333-5adc-4028-85c0-fca086467480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'ค้นหา']</value>
      <webElementGuid>962a98b4-a803-41d5-9da7-84f83a39b658</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
