<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>1c0c0339-9955-4913-9e46-0606de8758e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pr_id_8_content']/div/div/table/tbody/tr[2]/td[2]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c7efe1dc-ecf9-4c22-9840-79657d2d5912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ธรรมิกา สุขประเสริญ</value>
      <webElementGuid>5a60b488-f4cc-4b11-affd-2e0e19a87800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_8_content&quot;)/div[@class=&quot;p-datatable p-component p-datatable-selectable p-datatable-responsive-scroll&quot;]/div[@class=&quot;p-datatable-wrapper&quot;]/table[@class=&quot;p-datatable-table&quot;]/tbody[@class=&quot;p-datatable-tbody&quot;]/tr[@class=&quot;p-selectable-row p-row-odd&quot;]/td[2]/div[@class=&quot;tooltip-data&quot;]/span[1]</value>
      <webElementGuid>b78a91d5-0944-4d72-9983-45a4597770d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_8_content']/div/div/table/tbody/tr[2]/td[2]/div/span</value>
      <webElementGuid>8ca488c8-c4f4-48db-a4de-677db22cfd98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EMP002'])[1]/following::span[1]</value>
      <webElementGuid>7bf3c651-3316-4f8b-bd9f-a86545bea94e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ปฏิบัติการ'])[1]/following::span[2]</value>
      <webElementGuid>3f94f0d5-7876-42d6-be77-8e396f913b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='กรรมการผู้จัดการ'])[2]/preceding::span[1]</value>
      <webElementGuid>66b12d78-39c7-4006-8235-18063665d7ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='กรรมการผู้จัดการ'])[3]/preceding::span[2]</value>
      <webElementGuid>1d400b64-15be-4511-98b5-984f8de60244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ธรรมิกา สุขประเสริญ']/parent::*</value>
      <webElementGuid>ff2a1a44-ed92-434f-ab60-141968a74093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/span</value>
      <webElementGuid>ae89a135-4e8e-4ec4-b54b-aa4c27ced0e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'ธรรมิกา สุขประเสริญ' or . = 'ธรรมิกา สุขประเสริญ')]</value>
      <webElementGuid>037c13eb-4e2f-4c9d-a3ba-240019a625af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
