<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnSubMenuFormTemplate</name>
   <tag></tag>
   <elementGuidId>c57f823d-d9df-421d-b3ab-a074329bfecf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@href = '/Settings?name=TemplateList']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>01cbb8a2-2bba-4f2f-b9dc-c6a066088e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Settings?name=TemplateList</value>
      <webElementGuid>b15e6327-54ea-4c5a-baf6-b7374f9612ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Form_Template</value>
      <webElementGuid>f53ad04b-35f7-4b4b-8020-d1ac8b2df771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-submenu</value>
      <webElementGuid>d0bd7571-7cf2-4a5e-bf27-b9088a4d4203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Form Template</value>
      <webElementGuid>5ebeaac9-7367-41c4-a5a3-cf35ae8f68cd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
