<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnSubMenuDelegateList</name>
   <tag></tag>
   <elementGuidId>da9d48c7-e8d9-4fed-ba43-c111af115e48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@href = '/Settings?name=DelegateList' and @class = 'a-button-submenu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2d11416a-df1e-40df-a95e-2134961c749d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Settings?name=DelegateList</value>
      <webElementGuid>2713e257-a6aa-4ec4-8a37-6871ce8b45fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-submenu</value>
      <webElementGuid>7c047517-e388-427b-bc45-8b34a117ee15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delegate List</value>
      <webElementGuid>6605d564-cb85-4fb9-a447-cf88b415fa00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Delegate_List</value>
      <webElementGuid>2390a8de-d38c-4da2-ad16-2e8be71d37f1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
