<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnSubMenuApprovalMatrix</name>
   <tag></tag>
   <elementGuidId>0fe5b797-f403-475b-832a-a5aa6ad24ac8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@href = '/Settings?name=ApprovalMatrix' and @class = 'a-button-submenu' and (contains(text(), 'Approval Matrix') or contains(., 'Approval Matrix'))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Settings?name=ApprovalMatrix</value>
      <webElementGuid>2af6132b-89a1-4fa4-af3f-1dc93144cbf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e6cf9d1e-6dff-4515-9bf0-cd11b88b8b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-submenu</value>
      <webElementGuid>7b208461-f925-43fc-a3a9-5a1c84fd021f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Approval Matrix</value>
      <webElementGuid>eb156d61-e5c6-47ae-82fd-029b4a3ed0ed</webElementGuid>
   </webElementProperties>
</WebElementEntity>
