<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnSubMenuPosition</name>
   <tag></tag>
   <elementGuidId>f759742c-7237-4a81-b105-8d9ff2da74b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@href = '/Settings?name=Position']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Position</value>
      <webElementGuid>3f06f6bf-097d-430d-967e-efe8d077d946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>24e0ee57-fc92-4cab-8c2a-fe644304e118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Settings?name=Position</value>
      <webElementGuid>abe7daef-3d47-4f9f-a094-753616b8dd4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-submenu</value>
      <webElementGuid>e44692c4-ce02-420c-bdce-783335e8ef17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Position</value>
      <webElementGuid>d644a12f-a5c1-4e70-97fb-5f0f486ea3be</webElementGuid>
   </webElementProperties>
</WebElementEntity>
